<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.5 The pivot: distributions of statistics | Statistics and Econometrics with R</title>
  <meta name="description" content="<p>A first course in statistics and econometrics, where every idea is developed
on paper and then immediately carried out in R.</p>" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="1.5 The pivot: distributions of statistics | Statistics and Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>A first course in statistics and econometrics, where every idea is developed
on paper and then immediately carried out in R.</p>" />
  <meta name="github-repo" content="kedarkulkarni1991/stats-econometrics-r" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.5 The pivot: distributions of statistics | Statistics and Econometrics with R" />
  
  <meta name="twitter:description" content="<p>A first course in statistics and econometrics, where every idea is developed
on paper and then immediately carried out in R.</p>" />
  

<meta name="author" content="Kedar Kulkarni" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="d2i-population.html"/>
<link rel="next" href="d2i-average.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><strong>Statistics &amp; Econometrics with R</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i>How to use this book</a></li>
<li class="chapter" data-level="" data-path="what-you-need.html"><a href="what-you-need.html"><i class="fa fa-check"></i>What you need</a></li>
<li class="chapter" data-level="" data-path="notation-used-throughout.html"><a href="notation-used-throughout.html"><i class="fa fa-check"></i>Notation used throughout</a></li>
<li class="chapter" data-level="" data-path="a-note-on-the-data.html"><a href="a-note-on-the-data.html"><i class="fa fa-check"></i>A note on the data</a></li>
<li class="chapter" data-level="" data-path="licence-and-citation.html"><a href="licence-and-citation.html"><i class="fa fa-check"></i>Licence and citation</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="description-to-inference.html"><a href="description-to-inference.html"><i class="fa fa-check"></i><b>1</b> From Description to Inference</a>
<ul>
<li class="chapter" data-level="1.1" data-path="d2i-descriptive.html"><a href="d2i-descriptive.html"><i class="fa fa-check"></i><b>1.1</b> What we can already do</a></li>
<li class="chapter" data-level="1.2" data-path="d2i-two-questions.html"><a href="d2i-two-questions.html"><i class="fa fa-check"></i><b>1.2</b> Where description runs out</a></li>
<li class="chapter" data-level="1.3" data-path="d2i-distribution.html"><a href="d2i-distribution.html"><i class="fa fa-check"></i><b>1.3</b> What a distribution actually is</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="d2i-distribution.html"><a href="d2i-distribution.html#d2i-degenerate"><i class="fa fa-check"></i><b>1.3.1</b> Randomness is not optional</a></li>
<li class="chapter" data-level="1.3.2" data-path="d2i-distribution.html"><a href="d2i-distribution.html#d2i-expectation"><i class="fa fa-check"></i><b>1.3.2</b> Expectation as a long-run average</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="d2i-population.html"><a href="d2i-population.html"><i class="fa fa-check"></i><b>1.4</b> Population, sample, and the assumption that licenses everything</a></li>
<li class="chapter" data-level="1.5" data-path="d2i-sampling-distribution.html"><a href="d2i-sampling-distribution.html"><i class="fa fa-check"></i><b>1.5</b> The pivot: distributions of statistics</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="d2i-sampling-distribution.html"><a href="d2i-sampling-distribution.html#d2i-cards"><i class="fa fa-check"></i><b>1.5.1</b> A worked example: a deck of cards</a></li>
<li class="chapter" data-level="1.5.2" data-path="d2i-sampling-distribution.html"><a href="d2i-sampling-distribution.html#d2i-samplesize"><i class="fa fa-check"></i><b>1.5.2</b> What happens as the sample grows</a></li>
<li class="chapter" data-level="1.5.3" data-path="d2i-sampling-distribution.html"><a href="d2i-sampling-distribution.html#d2i-asi-sampling"><i class="fa fa-check"></i><b>1.5.3</b> The same logic on Indian data</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="d2i-average.html"><a href="d2i-average.html"><i class="fa fa-check"></i><b>1.6</b> The average is not the distribution</a></li>
<li class="chapter" data-level="1.7" data-path="d2i-what-goes-wrong.html"><a href="d2i-what-goes-wrong.html"><i class="fa fa-check"></i><b>1.7</b> What can go wrong before any mathematics</a></li>
<li class="chapter" data-level="1.8" data-path="d2i-summary.html"><a href="d2i-summary.html"><i class="fa fa-check"></i><b>1.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="one-sample.html"><a href="one-sample.html"><i class="fa fa-check"></i><b>2</b> Hypothesis Testing: One Sample</a>
<ul>
<li class="chapter" data-level="2.1" data-path="os-problem.html"><a href="os-problem.html"><i class="fa fa-check"></i><b>2.1</b> The problem, before any formulas</a></li>
<li class="chapter" data-level="2.2" data-path="os-hypotheses.html"><a href="os-hypotheses.html"><i class="fa fa-check"></i><b>2.2</b> Naming the two hypotheses</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="os-hypotheses.html"><a href="os-hypotheses.html#os-which-hypothesis"><i class="fa fa-check"></i><b>2.2.1</b> Which hypothesis does the claim go in?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="os-critical.html"><a href="os-critical.html"><i class="fa fa-check"></i><b>2.3</b> How far is too far?</a></li>
<li class="chapter" data-level="2.4" data-path="os-worked.html"><a href="os-worked.html"><i class="fa fa-check"></i><b>2.4</b> The worked example, both ways</a>
<ul>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#on-paper"><i class="fa fa-check"></i>On paper</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#the-same-thing-in-r"><i class="fa fa-check"></i>The same thing in R</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#letting-a-package-do-it"><i class="fa fa-check"></i>Letting a package do it</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="os-pvalue.html"><a href="os-pvalue.html"><i class="fa fa-check"></i><b>2.5</b> What a <span class="math inline">\(p\)</span>-value actually says</a></li>
<li class="chapter" data-level="2.6" data-path="os-ci.html"><a href="os-ci.html"><i class="fa fa-check"></i><b>2.6</b> Confidence intervals are the same test in disguise</a></li>
<li class="chapter" data-level="2.7" data-path="os-ttest.html"><a href="os-ttest.html"><i class="fa fa-check"></i><b>2.7</b> When <span class="math inline">\(\sigma\)</span> is unknown: the <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#settling-the-question-with-the-actual-class"><i class="fa fa-check"></i>Settling the question with the actual class</a></li>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#worked-example"><i class="fa fa-check"></i>Worked example</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="os-onetailed.html"><a href="os-onetailed.html"><i class="fa fa-check"></i><b>2.8</b> One-tailed tests</a>
<ul>
<li class="chapter" data-level="" data-path="os-onetailed.html"><a href="os-onetailed.html#the-one-sided-interval-looks-backwards"><i class="fa fa-check"></i>The one-sided interval looks backwards</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="os-reference.html"><a href="os-reference.html"><i class="fa fa-check"></i><b>2.9</b> Reference tables</a></li>
<li class="chapter" data-level="2.10" data-path="os-exercises.html"><a href="os-exercises.html"><i class="fa fa-check"></i><b>2.10</b> Practice problems</a></li>
<li class="chapter" data-level="2.11" data-path="os-question-bank.html"><a href="os-question-bank.html"><i class="fa fa-check"></i><b>2.11</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#multiple-choice"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#short-reasoning"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#numerical"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="os-summary.html"><a href="os-summary.html"><i class="fa fa-check"></i><b>2.12</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li class="toc-after">Kedar Kulkarni · Azim Premji University<br>
<a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics and Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="d2i-sampling-distribution" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> The pivot: distributions of statistics<a href="d2i-sampling-distribution.html#d2i-sampling-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here is the conceptual step that makes inference possible, and it is the most
important idea in this unit.</p>
<p>Everything so far concerned the distribution of <strong>raw observations</strong>: repeat an
experiment, record individual outcomes, watch a pattern form. Now we shift
attention from raw observations to <strong>summaries of observations</strong>.</p>
<p>Instead of recording one die roll at a time, roll the die thirty times,
calculate the average, and record <em>only that average</em>. Then do the whole thing
again: a fresh thirty rolls, a fresh average. And again, hundreds of times.</p>
<p>The pattern formed by those averages is a <strong>sampling distribution</strong>.</p>
<div class="keyidea">
<p>The distribution of a <strong>random variable</strong> describes how raw observations vary.</p>
<p>A <strong>sampling distribution</strong> describes how a <em>statistic</em> — a sample mean, a
proportion, a standard deviation — varies across repeated samples of a fixed
size.</p>
<p>It answers the question inference actually turns on: <em>if I took another sample,
how different would my answer be?</em></p>
</div>
<div id="d2i-cards" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> A worked example: a deck of cards<a href="d2i-sampling-distribution.html#d2i-cards" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Take a standard deck as the population. Score the cards A = 1, J = 11, Q = 12,
K = 13, and 2 through 10 at face value. Because we built this population
ourselves, we know its parameters exactly — a luxury we will never have again.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="d2i-sampling-distribution.html#cb18-1" tabindex="-1"></a>deck <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">13</span>, <span class="at">times =</span> <span class="dv">4</span>)</span>
<span id="cb18-2"><a href="d2i-sampling-distribution.html#cb18-2" tabindex="-1"></a></span>
<span id="cb18-3"><a href="d2i-sampling-distribution.html#cb18-3" tabindex="-1"></a><span class="fu">c</span>(<span class="at">N =</span> <span class="fu">length</span>(deck), <span class="at">mu =</span> <span class="fu">mean</span>(deck), <span class="at">sigma =</span> <span class="fu">sd</span>(deck))</span></code></pre></div>
<pre><code>#&gt;      N     mu  sigma 
#&gt; 52.000  7.000  3.778</code></pre>
<p>The population mean is exactly <span class="math inline">\(\mu = 7\)</span>.</p>
<p>Now draw a sample of 10 cards and take its mean:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="d2i-sampling-distribution.html#cb20-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb20-2"><a href="d2i-sampling-distribution.html#cb20-2" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">sample</span>(deck, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>#&gt; [1] 5.7</code></pre>
<div class="watchout">
<p>Note <code>replace = TRUE</code>: each card is returned to the deck before the next draw.</p>
<p>That is not a technicality. It is what makes the draws <strong>independent</strong> — the
i.i.d. assumption from the previous section. Draw <em>without</em> replacement and
each card removed changes what remains, so the draws are dependent and the
sample mean varies slightly less than the theory predicts. (The adjustment is
called the finite population correction, and you can see it at work in the
exercises.)</p>
<p>Sampling with replacement is also the better model of what we usually mean.
When you survey 2,000 Indians you are not meaningfully depleting a population
of a billion.</p>
</div>
<p>Not 7. Draw again and you would get something else again. <strong>The sample mean is
itself a random variable</strong> — it has its own distribution, because it changes
every time you draw.</p>
<p>So let us look at that distribution. Repeat the exercise a thousand times:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="d2i-sampling-distribution.html#cb22-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb22-2"><a href="d2i-sampling-distribution.html#cb22-2" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(deck, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb22-3"><a href="d2i-sampling-distribution.html#cb22-3" tabindex="-1"></a></span>
<span id="cb22-4"><a href="d2i-sampling-distribution.html#cb22-4" tabindex="-1"></a><span class="fu">c</span>(<span class="at">mean_of_sample_means =</span> <span class="fu">mean</span>(sample_means),</span>
<span id="cb22-5"><a href="d2i-sampling-distribution.html#cb22-5" tabindex="-1"></a>  <span class="at">sd_of_sample_means   =</span> <span class="fu">sd</span>(sample_means))</span></code></pre></div>
<pre><code>#&gt; mean_of_sample_means   sd_of_sample_means 
#&gt;                6.932                1.201</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:d2i-sampdist-plot"></span>
<img src="stats-econometrics-r_files/figure-html/d2i-sampdist-plot-1.png" alt="One thousand sample means, each from 10 cards. Individual samples miss the population mean constantly. Their average lands almost exactly on it." width="90%" />
<p class="caption">
Figure 1.2: One thousand sample means, each from 10 cards. Individual samples miss the population mean constantly. Their average lands almost exactly on it.
</p>
</div>
<p>Two things happened, and both matter.</p>
<p><strong>The sample means are centred on the population mean.</strong> No single sample got
it right, but their average is 6.932 — essentially 7.
This is the result <span class="math inline">\(E(\bar{X}) = \mu\)</span>: the sample mean is an <strong>unbiased</strong>
estimator. It is not right, but it is not <em>systematically</em> wrong, which is a
different and far more useful property.</p>
<p><strong>The sample means vary much less than the cards do.</strong> The population standard
deviation is about 3.78; the sample means have a
standard deviation of about 1.2. Averaging has
cancelled out much of the noise.</p>
</div>
<div id="d2i-samplesize" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> What happens as the sample grows<a href="d2i-sampling-distribution.html#d2i-samplesize" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>That second observation is worth pushing on. What if we take bigger samples?</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="d2i-sampling-distribution.html#cb24-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb24-2"><a href="d2i-sampling-distribution.html#cb24-2" tabindex="-1"></a></span>
<span id="cb24-3"><a href="d2i-sampling-distribution.html#cb24-3" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>)</span>
<span id="cb24-4"><a href="d2i-sampling-distribution.html#cb24-4" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(sizes, <span class="cf">function</span>(n) {</span>
<span id="cb24-5"><a href="d2i-sampling-distribution.html#cb24-5" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">2000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(deck, <span class="at">size =</span> n, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb24-6"><a href="d2i-sampling-distribution.html#cb24-6" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">n =</span> n, <span class="at">mean =</span> <span class="fu">mean</span>(m), <span class="at">sd =</span> <span class="fu">sd</span>(m), <span class="at">theoretical_sd =</span> <span class="fu">sd</span>(deck) <span class="sc">/</span> <span class="fu">sqrt</span>(n))</span>
<span id="cb24-7"><a href="d2i-sampling-distribution.html#cb24-7" tabindex="-1"></a>}))</span>
<span id="cb24-8"><a href="d2i-sampling-distribution.html#cb24-8" tabindex="-1"></a></span>
<span id="cb24-9"><a href="d2i-sampling-distribution.html#cb24-9" tabindex="-1"></a><span class="fu">round</span>(results, <span class="dv">3</span>)</span></code></pre></div>
<pre><code>#&gt;       n  mean    sd theoretical_sd
#&gt; [1,]  5 6.932 1.688          1.690
#&gt; [2,] 10 7.022 1.165          1.195
#&gt; [3,] 20 7.009 0.845          0.845
#&gt; [4,] 40 7.019 0.597          0.597
#&gt; [5,] 80 6.996 0.415          0.422</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:d2i-nsizes-plot"></span>
<img src="stats-econometrics-r_files/figure-html/d2i-nsizes-plot-1.png" alt="Sampling distributions of the mean for growing sample sizes. The centre never moves. The spread collapses." width="90%" />
<p class="caption">
Figure 1.3: Sampling distributions of the mean for growing sample sizes. The centre never moves. The spread collapses.
</p>
</div>
<p>Every row is centred on 7 — the sample mean is unbiased at any sample size. But
the spread shrinks steadily, and in a completely predictable way. Compare the
last two columns: the observed standard deviation of the sample means matches
<span class="math inline">\(\sigma/\sqrt{n}\)</span> almost exactly.</p>
<div class="keyidea">
<p>Two results, which we will prove in a later unit:</p>
<p><span class="math display">\[E(\bar{X}) = \mu \qquad\qquad \mathrm{Var}(\bar{X}) = \frac{\sigma^2}{n}\]</span></p>
<p>The sample mean is centred on the population mean, and its spread falls as the
sample grows. The quantity <span class="math inline">\(\sigma/\sqrt{n}\)</span> is the <strong>standard error</strong>, and it
is the single most important number in applied statistics: it is how wrong you
should expect to be.</p>
</div>
<div class="watchout">
<p>Note the square root. To halve your standard error you must <strong>quadruple</strong> your
sample. Precision is expensive, and it grows more expensive the more of it you
already have.</p>
<p>This is why surveys of two thousand people are common and surveys of two lakh
people are not: the second costs a hundred times as much for about seven times
the precision.</p>
</div>
<div class="intuition">
<p>Look again at what just happened, because it is genuinely remarkable.</p>
<p>We began knowing nothing about how wrong a single sample would be. By studying
how the sample mean behaves <em>across many hypothetical samples</em>, we worked out
exactly how much it varies — and obtained a formula, <span class="math inline">\(\sigma/\sqrt{n}\)</span>, that
can be computed from a single real sample.</p>
<p>In practice you only ever draw one sample. The sampling distribution tells you
what would have happened had you drawn many, and that is enough to attach an
honest margin of error to the one you have.</p>
</div>
</div>
<div id="d2i-asi-sampling" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> The same logic on Indian data<a href="d2i-sampling-distribution.html#d2i-asi-sampling" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cards are a clean laboratory. Real data is messier, and the ASI figures let us
watch the same logic operate on something considerably less well behaved.</p>
<p>Treat the 32 state values as a population and sample from it:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="d2i-sampling-distribution.html#cb26-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb26-2"><a href="d2i-sampling-distribution.html#cb26-2" tabindex="-1"></a></span>
<span id="cb26-3"><a href="d2i-sampling-distribution.html#cb26-3" tabindex="-1"></a>pop <span class="ot">&lt;-</span> asi_2010<span class="sc">$</span>gva_crore</span>
<span id="cb26-4"><a href="d2i-sampling-distribution.html#cb26-4" tabindex="-1"></a>asi_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">2000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(pop, <span class="at">size =</span> <span class="dv">10</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb26-5"><a href="d2i-sampling-distribution.html#cb26-5" tabindex="-1"></a></span>
<span id="cb26-6"><a href="d2i-sampling-distribution.html#cb26-6" tabindex="-1"></a><span class="fu">c</span>(<span class="at">population_mean      =</span> <span class="fu">mean</span>(pop),</span>
<span id="cb26-7"><a href="d2i-sampling-distribution.html#cb26-7" tabindex="-1"></a>  <span class="at">mean_of_sample_means =</span> <span class="fu">mean</span>(asi_means),</span>
<span id="cb26-8"><a href="d2i-sampling-distribution.html#cb26-8" tabindex="-1"></a>  <span class="at">population_sd        =</span> <span class="fu">sd</span>(pop),</span>
<span id="cb26-9"><a href="d2i-sampling-distribution.html#cb26-9" tabindex="-1"></a>  <span class="at">se_of_sample_means   =</span> <span class="fu">sd</span>(asi_means))</span></code></pre></div>
<pre><code>#&gt;      population_mean mean_of_sample_means        population_sd 
#&gt;                25785                25715                36814 
#&gt;   se_of_sample_means 
#&gt;                11543</code></pre>
<p>Once again the sample means centre on the population mean, and once again they
vary far less than the underlying data. The machinery does not care that
industrial value added looks nothing like a deck of cards.</p>
<p>Which brings us to the feature of this data we have so far ignored.</p>
</div>
</div>
<script>
// Solutions are written as plain fenced divs in the source, so the PDF edition
// can typeset them as boxes. On the web they should stay hidden until asked
// for, so wrap each one in a <details> here.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll("div.solution").forEach(function (div) {
    var d = document.createElement("details");
    d.className = "solution";
    var s = document.createElement("summary");
    s.textContent = "Show the solution";
    d.appendChild(s);
    while (div.firstChild) d.appendChild(div.firstChild);
    div.parentNode.replaceChild(d, div);
  });
});
</script>
            </section>

          </div>
        </div>
      </div>
<a href="d2i-population.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="d2i-average.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/kedarkulkarni1991/stats-econometrics-r/edit/main/01-description-to-inference.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["stats-econometrics-r.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
