<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.8 Practice problems | Statistics and Econometrics with R</title>
  <meta name="description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="5.8 Practice problems | Statistics and Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  <meta name="github-repo" content="kedarkulkarni1991/stats-econometrics-r" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.8 Practice problems | Statistics and Econometrics with R" />
  
  <meta name="twitter:description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  

<meta name="author" content="Kedar Kulkarni" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ts-summary.html"/>
<link rel="next" href="ts-question-bank.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><strong>Statistics &amp; Econometrics with R</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i>How to use this book</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-the-book-in-order"><i class="fa fa-check"></i>Read the book in order</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#work-through-the-mathematics"><i class="fa fa-check"></i>Work through the mathematics</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#think-in-words-before-thinking-in-mathematics"><i class="fa fa-check"></i>Think in words before thinking in mathematics</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#write-the-code-yourself"><i class="fa fa-check"></i>Write the code yourself</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#think-before-calculating"><i class="fa fa-check"></i>Think before calculating</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#attempt-the-exercises-first"><i class="fa fa-check"></i>Attempt the exercises first</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#use-the-book-as-a-reference"><i class="fa fa-check"></i>Use the book as a reference</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#learn-by-connecting-ideas"><i class="fa fa-check"></i>Learn by connecting ideas</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a-note-on-the-data.html"><a href="a-note-on-the-data.html"><i class="fa fa-check"></i>A note on the data</a></li>
<li class="chapter" data-level="" data-path="what-you-need.html"><a href="what-you-need.html"><i class="fa fa-check"></i>What you need</a></li>
<li class="chapter" data-level="" data-path="mathematical-background.html"><a href="mathematical-background.html"><i class="fa fa-check"></i>Mathematical background</a></li>
<li class="chapter" data-level="" data-path="licence-and-citation.html"><a href="licence-and-citation.html"><i class="fa fa-check"></i>Licence and citation</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="towards-inference.html"><a href="towards-inference.html"><i class="fa fa-check"></i><b>1</b> Towards Inferential Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="u1-randomness.html"><a href="u1-randomness.html"><i class="fa fa-check"></i><b>1.1</b> Randomness and variation</a></li>
<li class="chapter" data-level="1.2" data-path="u1-describing.html"><a href="u1-describing.html"><i class="fa fa-check"></i><b>1.2</b> Describing variation</a></li>
<li class="chapter" data-level="1.3" data-path="u1-not-enough.html"><a href="u1-not-enough.html"><i class="fa fa-check"></i><b>1.3</b> The limits of descriptive statistics</a></li>
<li class="chapter" data-level="1.4" data-path="u1-frequentist.html"><a href="u1-frequentist.html"><i class="fa fa-check"></i><b>1.4</b> What if we repeated the survey?</a></li>
<li class="chapter" data-level="1.5" data-path="u1-lln.html"><a href="u1-lln.html"><i class="fa fa-check"></i><b>1.5</b> Why do larger samples give more reliable answers?</a></li>
<li class="chapter" data-level="1.6" data-path="u1-clt.html"><a href="u1-clt.html"><i class="fa fa-check"></i><b>1.6</b> The Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#a-simulation"><i class="fa fa-check"></i>A simulation</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#an-intuition"><i class="fa fa-check"></i>An intuition</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#how-large-is-large-enough"><i class="fa fa-check"></i>How large is “large enough”?</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#why-this-matters"><i class="fa fa-check"></i>Why this matters</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="u1-random-variables.html"><a href="u1-random-variables.html"><i class="fa fa-check"></i><b>1.7</b> A language for randomness</a>
<ul>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#random-variables"><i class="fa fa-check"></i>Random variables</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#realisations"><i class="fa fa-check"></i>Realisations</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#the-long-run-average"><i class="fa fa-check"></i>The long-run average</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#measuring-variation"><i class="fa fa-check"></i>Measuring variation</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#parameters-and-statistics"><i class="fa fa-check"></i>Parameters and statistics</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#a-summary-of-notation"><i class="fa fa-check"></i>A summary of notation</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="u1-what-goes-wrong.html"><a href="u1-what-goes-wrong.html"><i class="fa fa-check"></i><b>1.8</b> Before any mathematics can help</a></li>
<li class="chapter" data-level="1.9" data-path="u1-summary.html"><a href="u1-summary.html"><i class="fa fa-check"></i><b>1.9</b> Summary</a></li>
<li class="chapter" data-level="1.10" data-path="u1-practice.html"><a href="u1-practice.html"><i class="fa fa-check"></i><b>1.10</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="u1-practice.html"><a href="u1-practice.html#concept-checks"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="u1-practice.html"><a href="u1-practice.html#explain"><i class="fa fa-check"></i>Explain</a></li>
<li class="chapter" data-level="" data-path="u1-practice.html"><a href="u1-practice.html#numerical-problems"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="u1-practice.html"><a href="u1-practice.html#r-exercises"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="u1-question-bank.html"><a href="u1-question-bank.html"><i class="fa fa-check"></i><b>1.11</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="u1-question-bank.html"><a href="u1-question-bank.html#multiple-choice"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="u1-question-bank.html"><a href="u1-question-bank.html#short-reasoning"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="u1-question-bank.html"><a href="u1-question-bank.html#numerical"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="u1-looking-ahead.html"><a href="u1-looking-ahead.html"><i class="fa fa-check"></i><b>1.12</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="estimation.html"><a href="estimation.html"><i class="fa fa-check"></i><b>2</b> Estimation: Why the Sample Mean?</a>
<ul>
<li class="chapter" data-level="2.1" data-path="u2-problem.html"><a href="u2-problem.html"><i class="fa fa-check"></i><b>2.1</b> The problem of estimation</a></li>
<li class="chapter" data-level="2.2" data-path="u2-iid.html"><a href="u2-iid.html"><i class="fa fa-check"></i><b>2.2</b> When can a sample represent a population?</a></li>
<li class="chapter" data-level="2.3" data-path="u2-known-truth.html"><a href="u2-known-truth.html"><i class="fa fa-check"></i><b>2.3</b> How can we judge an estimator?</a>
<ul>
<li class="chapter" data-level="" data-path="u2-known-truth.html"><a href="u2-known-truth.html#u2-lab-pop"><i class="fa fa-check"></i>The population</a></li>
<li class="chapter" data-level="" data-path="u2-known-truth.html"><a href="u2-known-truth.html#u2-lab-one"><i class="fa fa-check"></i>One sample from it</a></li>
<li class="chapter" data-level="" data-path="u2-known-truth.html"><a href="u2-known-truth.html#u2-lab-many"><i class="fa fa-check"></i>A thousand samples</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="u2-centred.html"><a href="u2-centred.html"><i class="fa fa-check"></i><b>2.4</b> Is the sample mean centred on the truth?</a></li>
<li class="chapter" data-level="2.5" data-path="u2-precision.html"><a href="u2-precision.html"><i class="fa fa-check"></i><b>2.5</b> Why do larger samples fluctuate less?</a></li>
<li class="chapter" data-level="2.6" data-path="u2-lln-explained.html"><a href="u2-lln-explained.html"><i class="fa fa-check"></i><b>2.6</b> Why does the sample mean become more reliable?</a></li>
<li class="chapter" data-level="2.7" data-path="u2-cost.html"><a href="u2-cost.html"><i class="fa fa-check"></i><b>2.7</b> Why is precision expensive?</a></li>
<li class="chapter" data-level="2.8" data-path="u2-summary.html"><a href="u2-summary.html"><i class="fa fa-check"></i><b>2.8</b> Summary</a></li>
<li class="chapter" data-level="2.9" data-path="u2-practice.html"><a href="u2-practice.html"><i class="fa fa-check"></i><b>2.9</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="u2-practice.html"><a href="u2-practice.html#concept-checks-1"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="u2-practice.html"><a href="u2-practice.html#explain-1"><i class="fa fa-check"></i>Explain</a></li>
<li class="chapter" data-level="" data-path="u2-practice.html"><a href="u2-practice.html#numerical-problems-1"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="u2-practice.html"><a href="u2-practice.html#r-exercises-1"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="u2-question-bank.html"><a href="u2-question-bank.html"><i class="fa fa-check"></i><b>2.10</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="u2-question-bank.html"><a href="u2-question-bank.html#multiple-choice-1"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="u2-question-bank.html"><a href="u2-question-bank.html#short-reasoning-1"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="u2-question-bank.html"><a href="u2-question-bank.html#numerical-1"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="u2-looking-ahead.html"><a href="u2-looking-ahead.html"><i class="fa fa-check"></i><b>2.11</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="interval-estimation.html"><a href="interval-estimation.html"><i class="fa fa-check"></i><b>3</b> How Much Can One Sample Tell Us?</a>
<ul>
<li class="chapter" data-level="3.1" data-path="u3-single-sample.html"><a href="u3-single-sample.html"><i class="fa fa-check"></i><b>3.1</b> One sample, one number</a></li>
<li class="chapter" data-level="3.2" data-path="u3-variance.html"><a href="u3-variance.html"><i class="fa fa-check"></i><b>3.2</b> Estimating the standard error</a>
<ul>
<li class="chapter" data-level="" data-path="u3-variance.html"><a href="u3-variance.html#a-statistical-laboratory"><i class="fa fa-check"></i>A statistical laboratory</a></li>
<li class="chapter" data-level="" data-path="u3-variance.html"><a href="u3-variance.html#why-dividing-by-n-fails"><i class="fa fa-check"></i>Why dividing by n fails</a></li>
<li class="chapter" data-level="" data-path="u3-variance.html"><a href="u3-variance.html#why-the-correction-is-exactly-n-1"><i class="fa fa-check"></i>Why the correction is exactly n − 1</a></li>
<li class="chapter" data-level="" data-path="u3-variance.html"><a href="u3-variance.html#when-the-population-mean-is-known"><i class="fa fa-check"></i>When the population mean is known</a></li>
<li class="chapter" data-level="" data-path="u3-variance.html"><a href="u3-variance.html#back-to-the-standard-error"><i class="fa fa-check"></i>Back to the standard error</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="u3-proportion.html"><a href="u3-proportion.html"><i class="fa fa-check"></i><b>3.3</b> How do we estimate a proportion?</a>
<ul>
<li class="chapter" data-level="" data-path="u3-proportion.html"><a href="u3-proportion.html#how-much-does-a-sample-proportion-vary"><i class="fa fa-check"></i>How much does a sample proportion vary?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="u3-ci.html"><a href="u3-ci.html"><i class="fa fa-check"></i><b>3.4</b> From a point estimate to an interval</a>
<ul>
<li class="chapter" data-level="" data-path="u3-ci.html"><a href="u3-ci.html#building-the-interval"><i class="fa fa-check"></i>Building the interval</a></li>
<li class="chapter" data-level="" data-path="u3-ci.html"><a href="u3-ci.html#reversing-the-question"><i class="fa fa-check"></i>Reversing the question</a></li>
<li class="chapter" data-level="" data-path="u3-ci.html"><a href="u3-ci.html#what-does-95-actually-refer-to"><i class="fa fa-check"></i>What does 95% actually refer to?</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="u3-t.html"><a href="u3-t.html"><i class="fa fa-check"></i><b>3.5</b> What changes when σ is unknown?</a>
<ul>
<li class="chapter" data-level="" data-path="u3-t.html"><a href="u3-t.html#why-does-the-interval-change"><i class="fa fa-check"></i>Why does the interval change?</a></li>
<li class="chapter" data-level="" data-path="u3-t.html"><a href="u3-t.html#how-serious-is-the-problem"><i class="fa fa-check"></i>How serious is the problem?</a></li>
<li class="chapter" data-level="" data-path="u3-t.html"><a href="u3-t.html#the-t-distribution"><i class="fa fa-check"></i>The <span class="math inline">\(t\)</span> distribution</a></li>
<li class="chapter" data-level="" data-path="u3-t.html"><a href="u3-t.html#how-much-difference-does-it-make"><i class="fa fa-check"></i>How much difference does it make?</a></li>
<li class="chapter" data-level="" data-path="u3-t.html"><a href="u3-t.html#one-final-point"><i class="fa fa-check"></i>One final point</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="u3-samplesize.html"><a href="u3-samplesize.html"><i class="fa fa-check"></i><b>3.6</b> How large a sample do we need?</a>
<ul>
<li class="chapter" data-level="" data-path="u3-samplesize.html"><a href="u3-samplesize.html#intervals-for-a-proportion"><i class="fa fa-check"></i>Intervals for a proportion</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="u3-onesided.html"><a href="u3-onesided.html"><i class="fa fa-check"></i><b>3.7</b> When only one direction matters</a></li>
<li class="chapter" data-level="3.8" data-path="u3-misreadings.html"><a href="u3-misreadings.html"><i class="fa fa-check"></i><b>3.8</b> What a confidence interval does not mean</a>
<ul>
<li class="chapter" data-level="" data-path="u3-misreadings.html"><a href="u3-misreadings.html#statement-1-the-probability-the-mean-is-inside"><i class="fa fa-check"></i>Statement 1: the probability the mean is inside</a></li>
<li class="chapter" data-level="" data-path="u3-misreadings.html"><a href="u3-misreadings.html#statement-2-the-spread-of-the-population"><i class="fa fa-check"></i>Statement 2: the spread of the population</a></li>
<li class="chapter" data-level="" data-path="u3-misreadings.html"><a href="u3-misreadings.html#statement-3-two-intervals-that-overlap"><i class="fa fa-check"></i>Statement 3: two intervals that overlap</a></li>
<li class="chapter" data-level="" data-path="u3-misreadings.html"><a href="u3-misreadings.html#statement-4-a-wider-interval"><i class="fa fa-check"></i>Statement 4: a wider interval</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="u3-summary.html"><a href="u3-summary.html"><i class="fa fa-check"></i><b>3.9</b> Summary</a></li>
<li class="chapter" data-level="3.10" data-path="u3-practice.html"><a href="u3-practice.html"><i class="fa fa-check"></i><b>3.10</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="u3-practice.html"><a href="u3-practice.html#concept-checks-2"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="u3-practice.html"><a href="u3-practice.html#explain-2"><i class="fa fa-check"></i>Explain</a></li>
<li class="chapter" data-level="" data-path="u3-practice.html"><a href="u3-practice.html#numerical-problems-2"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="u3-practice.html"><a href="u3-practice.html#r-exercises-2"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="u3-question-bank.html"><a href="u3-question-bank.html"><i class="fa fa-check"></i><b>3.11</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="u3-question-bank.html"><a href="u3-question-bank.html#multiple-choice-2"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="u3-question-bank.html"><a href="u3-question-bank.html#short-reasoning-2"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="u3-question-bank.html"><a href="u3-question-bank.html#numerical-2"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="u3-looking-ahead.html"><a href="u3-looking-ahead.html"><i class="fa fa-check"></i><b>3.12</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="one-sample.html"><a href="one-sample.html"><i class="fa fa-check"></i><b>4</b> Hypothesis Testing: One Sample</a>
<ul>
<li class="chapter" data-level="4.1" data-path="os-problem.html"><a href="os-problem.html"><i class="fa fa-check"></i><b>4.1</b> The problem, before any formulas</a></li>
<li class="chapter" data-level="4.2" data-path="os-hypotheses.html"><a href="os-hypotheses.html"><i class="fa fa-check"></i><b>4.2</b> Naming the two hypotheses</a>
<ul>
<li class="chapter" data-level="" data-path="os-hypotheses.html"><a href="os-hypotheses.html#why-begin-by-assuming-the-claim-is-true"><i class="fa fa-check"></i>Why begin by assuming the claim is true?</a></li>
<li class="chapter" data-level="4.2.1" data-path="os-hypotheses.html"><a href="os-hypotheses.html#os-which-hypothesis"><i class="fa fa-check"></i><b>4.2.1</b> Which hypothesis does the claim go in?</a></li>
<li class="chapter" data-level="" data-path="os-hypotheses.html"><a href="os-hypotheses.html#where-the-equality-goes"><i class="fa fa-check"></i>Where the equality goes</a></li>
<li class="chapter" data-level="" data-path="os-hypotheses.html"><a href="os-hypotheses.html#the-cat-report-worked-through"><i class="fa fa-check"></i>The CAT report, worked through</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="os-pvalue.html"><a href="os-pvalue.html"><i class="fa fa-check"></i><b>4.3</b> What a p-value actually says</a>
<ul>
<li class="chapter" data-level="" data-path="os-pvalue.html"><a href="os-pvalue.html#four-ways-to-read-it-backwards"><i class="fa fa-check"></i>Four ways to read it backwards</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="os-critical.html"><a href="os-critical.html"><i class="fa fa-check"></i><b>4.4</b> How far is too far?</a>
<ul>
<li class="chapter" data-level="" data-path="os-critical.html"><a href="os-critical.html#choosing-the-cutoff"><i class="fa fa-check"></i>Choosing the cutoff</a></li>
<li class="chapter" data-level="" data-path="os-critical.html"><a href="os-critical.html#the-decision-rule"><i class="fa fa-check"></i>The decision rule</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="os-worked.html"><a href="os-worked.html"><i class="fa fa-check"></i><b>4.5</b> The worked example, both ways</a>
<ul>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#on-paper"><i class="fa fa-check"></i>On paper</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#the-same-thing-in-r"><i class="fa fa-check"></i>The same thing in R</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#letting-a-package-do-it"><i class="fa fa-check"></i>Letting a package do it</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="os-ci.html"><a href="os-ci.html"><i class="fa fa-check"></i><b>4.6</b> The same test, viewed as an interval</a>
<ul>
<li class="chapter" data-level="" data-path="os-ci.html"><a href="os-ci.html#testing-every-possible-claim-at-once"><i class="fa fa-check"></i>Testing every possible claim at once</a></li>
<li class="chapter" data-level="" data-path="os-ci.html"><a href="os-ci.html#so-why-keep-both"><i class="fa fa-check"></i>So why keep both?</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="os-ttest.html"><a href="os-ttest.html"><i class="fa fa-check"></i><b>4.7</b> When σ is unknown: the t-test</a>
<ul>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#settling-the-question-with-the-actual-class"><i class="fa fa-check"></i>Settling the question with the actual class</a></li>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#worked-example"><i class="fa fa-check"></i>Worked example</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="os-onetailed.html"><a href="os-onetailed.html"><i class="fa fa-check"></i><b>4.8</b> One-tailed tests</a>
<ul>
<li class="chapter" data-level="" data-path="os-onetailed.html"><a href="os-onetailed.html#unknown-%CF%83-the-one-sided-t-test"><i class="fa fa-check"></i>Unknown σ: the one-sided t-test</a></li>
<li class="chapter" data-level="" data-path="os-onetailed.html"><a href="os-onetailed.html#the-one-sided-interval-looks-backwards"><i class="fa fa-check"></i>The one-sided interval looks backwards</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="os-errors.html"><a href="os-errors.html"><i class="fa fa-check"></i><b>4.9</b> Two ways to be wrong</a>
<ul>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#the-two-errors"><i class="fa fa-check"></i>The two errors</a></li>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#the-umpires-call"><i class="fa fa-check"></i>The umpire’s call</a></li>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#why-errors-happen-at-all"><i class="fa fa-check"></i>Why errors happen at all</a></li>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#power"><i class="fa fa-check"></i>Power</a></li>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#working-it-out"><i class="fa fa-check"></i>Working it out</a></li>
<li class="chapter" data-level="" data-path="os-errors.html"><a href="os-errors.html#what-determines-power"><i class="fa fa-check"></i>What determines power</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="os-reference.html"><a href="os-reference.html"><i class="fa fa-check"></i><b>4.10</b> Reference tables</a></li>
<li class="chapter" data-level="4.11" data-path="os-summary.html"><a href="os-summary.html"><i class="fa fa-check"></i><b>4.11</b> Summary</a></li>
<li class="chapter" data-level="4.12" data-path="os-exercises.html"><a href="os-exercises.html"><i class="fa fa-check"></i><b>4.12</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="os-exercises.html"><a href="os-exercises.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i>Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="4.13" data-path="os-question-bank.html"><a href="os-question-bank.html"><i class="fa fa-check"></i><b>4.13</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#multiple-choice-3"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#short-reasoning-3"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#numerical-3"><i class="fa fa-check"></i>Numerical</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#errors-and-power"><i class="fa fa-check"></i>Errors and power</a></li>
</ul></li>
<li class="chapter" data-level="4.14" data-path="os-looking-ahead.html"><a href="os-looking-ahead.html"><i class="fa fa-check"></i><b>4.14</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="two-sample.html"><a href="two-sample.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Testing: Two Samples</a>
<ul>
<li class="chapter" data-level="5.1" data-path="ts-motivation.html"><a href="ts-motivation.html"><i class="fa fa-check"></i><b>5.1</b> Comparing two groups</a></li>
<li class="chapter" data-level="5.2" data-path="ts-sampling.html"><a href="ts-sampling.html"><i class="fa fa-check"></i><b>5.2</b> What does a difference of means do across samples?</a></li>
<li class="chapter" data-level="5.3" data-path="ts-known.html"><a href="ts-known.html"><i class="fa fa-check"></i><b>5.3</b> Testing the difference when σ is known</a>
<ul>
<li class="chapter" data-level="" data-path="ts-known.html"><a href="ts-known.html#conventional-against-high-yielding-wheat"><i class="fa fa-check"></i>Conventional against high-yielding wheat</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="ts-unknown.html"><a href="ts-unknown.html"><i class="fa fa-check"></i><b>5.4</b> When σ is unknown</a>
<ul>
<li class="chapter" data-level="" data-path="ts-unknown.html"><a href="ts-unknown.html#large-samples"><i class="fa fa-check"></i>Large samples</a></li>
<li class="chapter" data-level="" data-path="ts-unknown.html"><a href="ts-unknown.html#equal-variances-the-pooled-estimator"><i class="fa fa-check"></i>Equal variances: the pooled estimator</a></li>
<li class="chapter" data-level="" data-path="ts-unknown.html"><a href="ts-unknown.html#unequal-variances-welchs-test"><i class="fa fa-check"></i>Unequal variances: Welch’s test</a></li>
<li class="chapter" data-level="" data-path="ts-unknown.html"><a href="ts-unknown.html#do-north-and-south-indian-students-differ-in-height"><i class="fa fa-check"></i>Do North and South Indian students differ in height?</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="ts-paired.html"><a href="ts-paired.html"><i class="fa fa-check"></i><b>5.5</b> When two samples are not really two samples</a>
<ul>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#something-is-wrong"><i class="fa fa-check"></i>Something is wrong</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#what-the-two-sample-test-assumed"><i class="fa fa-check"></i>What the two-sample test assumed</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#two-sources-of-variation"><i class="fa fa-check"></i>Two sources of variation</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#removing-what-we-do-not-care-about"><i class="fa fa-check"></i>Removing what we do not care about</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#the-statistical-model"><i class="fa fa-check"></i>The statistical model</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#setting-up-the-hypotheses"><i class="fa fa-check"></i>Setting up the hypotheses</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#estimating-the-mean-difference"><i class="fa fa-check"></i>Estimating the mean difference</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#the-test-statistic"><i class="fa fa-check"></i>The test statistic</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#confidence-interval"><i class="fa fa-check"></i>Confidence interval</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#doing-it-in-r"><i class="fa fa-check"></i>Doing it in R</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#why-did-the-answer-change-so-much"><i class="fa fa-check"></i>Why did the answer change so much?</a></li>
<li class="chapter" data-level="" data-path="ts-paired.html"><a href="ts-paired.html#when-should-we-use-a-paired-test"><i class="fa fa-check"></i>When should we use a paired test?</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="ts-causal.html"><a href="ts-causal.html"><i class="fa fa-check"></i><b>5.6</b> A difference is not an effect</a>
<ul>
<li class="chapter" data-level="" data-path="ts-causal.html"><a href="ts-causal.html#the-difference-is-significant-and-trivial"><i class="fa fa-check"></i>The difference is significant and trivial</a></li>
<li class="chapter" data-level="" data-path="ts-causal.html"><a href="ts-causal.html#the-groups-were-not-assigned"><i class="fa fa-check"></i>The groups were not assigned</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="ts-summary.html"><a href="ts-summary.html"><i class="fa fa-check"></i><b>5.7</b> Summary</a></li>
<li class="chapter" data-level="5.8" data-path="ts-practice.html"><a href="ts-practice.html"><i class="fa fa-check"></i><b>5.8</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="ts-practice.html"><a href="ts-practice.html#concept-checks-3"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="ts-practice.html"><a href="ts-practice.html#explain-3"><i class="fa fa-check"></i>Explain</a></li>
<li class="chapter" data-level="" data-path="ts-practice.html"><a href="ts-practice.html#numerical-problems-3"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="ts-practice.html"><a href="ts-practice.html#r-exercises-3"><i class="fa fa-check"></i>R exercises</a></li>
<li class="chapter" data-level="" data-path="ts-practice.html"><a href="ts-practice.html#paired-designs"><i class="fa fa-check"></i>Paired designs</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="ts-question-bank.html"><a href="ts-question-bank.html"><i class="fa fa-check"></i><b>5.9</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#multiple-choice-4"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#short-reasoning-4"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#numerical-4"><i class="fa fa-check"></i>Numerical</a></li>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#paired-designs-1"><i class="fa fa-check"></i>Paired designs</a></li>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#paired-reasoning"><i class="fa fa-check"></i>Paired reasoning</a></li>
<li class="chapter" data-level="" data-path="ts-question-bank.html"><a href="ts-question-bank.html#paired-numerical"><i class="fa fa-check"></i>Paired numerical</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="ts-looking-ahead.html"><a href="ts-looking-ahead.html"><i class="fa fa-check"></i><b>5.10</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="simple-regression.html"><a href="simple-regression.html"><i class="fa fa-check"></i><b>6</b> The Simple Regression Model</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sr-motivation.html"><a href="sr-motivation.html"><i class="fa fa-check"></i><b>6.1</b> From comparing groups to modelling relationships</a>
<ul>
<li class="chapter" data-level="" data-path="sr-motivation.html"><a href="sr-motivation.html#the-experiment-we-cannot-run"><i class="fa fa-check"></i>The experiment we cannot run</a></li>
<li class="chapter" data-level="" data-path="sr-motivation.html"><a href="sr-motivation.html#the-question-has-changed"><i class="fa fa-check"></i>The question has changed</a></li>
<li class="chapter" data-level="" data-path="sr-motivation.html"><a href="sr-motivation.html#the-price-of-the-old-question"><i class="fa fa-check"></i>The price of the old question</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sr-prf.html"><a href="sr-prf.html"><i class="fa fa-check"></i><b>6.2</b> The population regression function</a></li>
<li class="chapter" data-level="6.3" data-path="sr-model.html"><a href="sr-model.html"><i class="fa fa-check"></i><b>6.3</b> From averages to observations</a></li>
<li class="chapter" data-level="6.4" data-path="sr-error.html"><a href="sr-error.html"><i class="fa fa-check"></i><b>6.4</b> The error term</a>
<ul>
<li class="chapter" data-level="" data-path="sr-error.html"><a href="sr-error.html#systematic-and-stochastic"><i class="fa fa-check"></i>Systematic and stochastic</a></li>
<li class="chapter" data-level="" data-path="sr-error.html"><a href="sr-error.html#what-the-two-parameters-mean"><i class="fa fa-check"></i>What the two parameters mean</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sr-assumptions.html"><a href="sr-assumptions.html"><i class="fa fa-check"></i><b>6.5</b> When does β₁ measure an effect?</a>
<ul>
<li class="chapter" data-level="" data-path="sr-assumptions.html"><a href="sr-assumptions.html#the-error-averages-zero"><i class="fa fa-check"></i>The error averages zero</a></li>
<li class="chapter" data-level="" data-path="sr-assumptions.html"><a href="sr-assumptions.html#the-error-is-unrelated-to-x"><i class="fa fa-check"></i>The error is unrelated to x</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="sr-srf.html"><a href="sr-srf.html"><i class="fa fa-check"></i><b>6.6</b> From the population to a sample</a>
<ul>
<li class="chapter" data-level="" data-path="sr-srf.html"><a href="sr-srf.html#two-sections-two-lines"><i class="fa fa-check"></i>Two sections, two lines</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="sr-ols.html"><a href="sr-ols.html"><i class="fa fa-check"></i><b>6.7</b> Which line should we fit?</a></li>
<li class="chapter" data-level="6.8" data-path="sr-summary.html"><a href="sr-summary.html"><i class="fa fa-check"></i><b>6.8</b> Summary</a></li>
<li class="chapter" data-level="6.9" data-path="sr-practice.html"><a href="sr-practice.html"><i class="fa fa-check"></i><b>6.9</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="sr-practice.html"><a href="sr-practice.html#concept-checks-4"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="sr-practice.html"><a href="sr-practice.html#explain-4"><i class="fa fa-check"></i>Explain</a></li>
<li class="chapter" data-level="" data-path="sr-practice.html"><a href="sr-practice.html#numerical-and-conceptual"><i class="fa fa-check"></i>Numerical and conceptual</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="sr-question-bank.html"><a href="sr-question-bank.html"><i class="fa fa-check"></i><b>6.10</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="sr-question-bank.html"><a href="sr-question-bank.html#multiple-choice-5"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="sr-question-bank.html"><a href="sr-question-bank.html#short-reasoning-5"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="sr-question-bank.html"><a href="sr-question-bank.html#numerical-5"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="sr-looking-ahead.html"><a href="sr-looking-ahead.html"><i class="fa fa-check"></i><b>6.11</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ols.html"><a href="ols.html"><i class="fa fa-check"></i><b>7</b> Ordinary Least Squares</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ols-derive.html"><a href="ols-derive.html"><i class="fa fa-check"></i><b>7.1</b> Deriving the estimators</a>
<ul>
<li class="chapter" data-level="" data-path="ols-derive.html"><a href="ols-derive.html#doing-it-by-hand-and-in-r"><i class="fa fa-check"></i>Doing it by hand and in R</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ols-fit.html"><a href="ols-fit.html"><i class="fa fa-check"></i><b>7.2</b> What the fitted line guarantees</a>
<ul>
<li class="chapter" data-level="" data-path="ols-fit.html"><a href="ols-fit.html#how-much-of-the-variation-has-the-line-accounted-for"><i class="fa fa-check"></i>How much of the variation has the line accounted for?</a></li>
<li class="chapter" data-level="" data-path="ols-fit.html"><a href="ols-fit.html#from-one-observation-to-all-of-them"><i class="fa fa-check"></i>From one observation to all of them</a></li>
<li class="chapter" data-level="" data-path="ols-fit.html"><a href="ols-fit.html#the-coefficient-of-determination"><i class="fa fa-check"></i>The coefficient of determination</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ols-sampling.html"><a href="ols-sampling.html"><i class="fa fa-check"></i><b>7.3</b> Every sample gives a different line</a>
<ul>
<li class="chapter" data-level="" data-path="ols-sampling.html"><a href="ols-sampling.html#looking-only-at-the-slopes"><i class="fa fa-check"></i>Looking only at the slopes</a></li>
<li class="chapter" data-level="" data-path="ols-sampling.html"><a href="ols-sampling.html#what-makes-the-distribution-narrow"><i class="fa fa-check"></i>What makes the distribution narrow?</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ols-unbiased.html"><a href="ols-unbiased.html"><i class="fa fa-check"></i><b>7.4</b> Why does OLS get the right answer on average?</a></li>
<li class="chapter" data-level="7.5" data-path="ols-variance.html"><a href="ols-variance.html"><i class="fa fa-check"></i><b>7.5</b> How precise is OLS?</a>
<ul>
<li class="chapter" data-level="" data-path="ols-variance.html"><a href="ols-variance.html#the-formula"><i class="fa fa-check"></i>The formula</a></li>
<li class="chapter" data-level="" data-path="ols-variance.html"><a href="ols-variance.html#does-it-work"><i class="fa fa-check"></i>Does it work?</a></li>
<li class="chapter" data-level="" data-path="ols-variance.html"><a href="ols-variance.html#why-the-denominator-matters"><i class="fa fa-check"></i>Why the denominator matters</a></li>
<li class="chapter" data-level="" data-path="ols-variance.html"><a href="ols-variance.html#where-the-formula-comes-from"><i class="fa fa-check"></i>Where the formula comes from</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ols-hetero.html"><a href="ols-hetero.html"><i class="fa fa-check"></i><b>7.6</b> When the error variance is not constant</a>
<ul>
<li class="chapter" data-level="" data-path="ols-hetero.html"><a href="ols-hetero.html#what-it-looks-like"><i class="fa fa-check"></i>What it looks like</a></li>
<li class="chapter" data-level="" data-path="ols-hetero.html"><a href="ols-hetero.html#does-heteroskedasticity-matter"><i class="fa fa-check"></i>Does heteroskedasticity matter?</a></li>
<li class="chapter" data-level="" data-path="ols-hetero.html"><a href="ols-hetero.html#how-wrong"><i class="fa fa-check"></i>How wrong?</a></li>
<li class="chapter" data-level="" data-path="ols-hetero.html"><a href="ols-hetero.html#robust-standard-errors"><i class="fa fa-check"></i>Robust standard errors</a></li>
<li class="chapter" data-level="" data-path="ols-hetero.html"><a href="ols-hetero.html#the-wider-lesson"><i class="fa fa-check"></i>The wider lesson</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="ols-inference.html"><a href="ols-inference.html"><i class="fa fa-check"></i><b>7.7</b> Inference about the slope</a></li>
<li class="chapter" data-level="7.8" data-path="ols-causal.html"><a href="ols-causal.html"><i class="fa fa-check"></i><b>7.8</b> Two students</a>
<ul>
<li class="chapter" data-level="" data-path="ols-causal.html"><a href="ols-causal.html#what-must-be-true"><i class="fa fa-check"></i>What must be true</a></li>
<li class="chapter" data-level="" data-path="ols-causal.html"><a href="ols-causal.html#none-of-this-appears-in-the-output"><i class="fa fa-check"></i>None of this appears in the output</a></li>
<li class="chapter" data-level="" data-path="ols-causal.html"><a href="ols-causal.html#where-to-go-from-here"><i class="fa fa-check"></i>Where to go from here</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="ols-summary.html"><a href="ols-summary.html"><i class="fa fa-check"></i><b>7.9</b> Summary</a></li>
<li class="chapter" data-level="7.10" data-path="ols-practice.html"><a href="ols-practice.html"><i class="fa fa-check"></i><b>7.10</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="ols-practice.html"><a href="ols-practice.html#numerical-problems-4"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="ols-practice.html"><a href="ols-practice.html#concept-checks-5"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="ols-practice.html"><a href="ols-practice.html#r-exercises-4"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="ols-question-bank.html"><a href="ols-question-bank.html"><i class="fa fa-check"></i><b>7.11</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="ols-question-bank.html"><a href="ols-question-bank.html#multiple-choice-6"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="ols-question-bank.html"><a href="ols-question-bank.html#short-reasoning-6"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="ols-question-bank.html"><a href="ols-question-bank.html#numerical-6"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="7.12" data-path="ols-looking-ahead.html"><a href="ols-looking-ahead.html"><i class="fa fa-check"></i><b>7.12</b> Looking ahead</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>8</b> Multiple Regression: Holding Other Things Equal</a>
<ul>
<li class="chapter" data-level="8.1" data-path="mlr-motivation.html"><a href="mlr-motivation.html"><i class="fa fa-check"></i><b>8.1</b> Why one variable is not enough</a></li>
<li class="chapter" data-level="8.2" data-path="mlr-model.html"><a href="mlr-model.html"><i class="fa fa-check"></i><b>8.2</b> Holding other things equal</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-model.html"><a href="mlr-model.html#a-different-comparison"><i class="fa fa-check"></i>A different comparison</a></li>
<li class="chapter" data-level="" data-path="mlr-model.html"><a href="mlr-model.html#an-example"><i class="fa fa-check"></i>An example</a></li>
<li class="chapter" data-level="" data-path="mlr-model.html"><a href="mlr-model.html#reading-the-other-coefficients"><i class="fa fa-check"></i>Reading the other coefficients</a></li>
<li class="chapter" data-level="" data-path="mlr-model.html"><a href="mlr-model.html#another-example"><i class="fa fa-check"></i>Another example</a></li>
<li class="chapter" data-level="" data-path="mlr-model.html"><a href="mlr-model.html#what-holding-fixed-does-not-mean"><i class="fa fa-check"></i>What “holding fixed” does not mean</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="mlr-fwl.html"><a href="mlr-fwl.html"><i class="fa fa-check"></i><b>8.3</b> What does “holding constant” actually mean?</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-fwl.html"><a href="mlr-fwl.html#predicting-attendance"><i class="fa fa-check"></i>Predicting attendance</a></li>
<li class="chapter" data-level="" data-path="mlr-fwl.html"><a href="mlr-fwl.html#using-only-what-could-not-be-predicted"><i class="fa fa-check"></i>Using only what could not be predicted</a></li>
<li class="chapter" data-level="" data-path="mlr-fwl.html"><a href="mlr-fwl.html#why-the-coefficient-changes"><i class="fa fa-check"></i>Why the coefficient changes</a></li>
<li class="chapter" data-level="" data-path="mlr-fwl.html"><a href="mlr-fwl.html#why-the-standard-error-usually-grows"><i class="fa fa-check"></i>Why the standard error usually grows</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="mlr-assumptions.html"><a href="mlr-assumptions.html"><i class="fa fa-check"></i><b>8.4</b> The assumptions of multiple regression</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-assumptions.html"><a href="mlr-assumptions.html#zero-conditional-mean"><i class="fa fa-check"></i>Zero conditional mean</a></li>
<li class="chapter" data-level="" data-path="mlr-assumptions.html"><a href="mlr-assumptions.html#no-perfect-collinearity"><i class="fa fa-check"></i>No perfect collinearity</a></li>
<li class="chapter" data-level="" data-path="mlr-assumptions.html"><a href="mlr-assumptions.html#when-controls-tell-us-the-same-thing"><i class="fa fa-check"></i>When controls tell us the same thing</a></li>
<li class="chapter" data-level="" data-path="mlr-assumptions.html"><a href="mlr-assumptions.html#the-trade"><i class="fa fa-check"></i>The trade</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="mlr-t.html"><a href="mlr-t.html"><i class="fa fa-check"></i><b>8.5</b> Testing one coefficient</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-t.html"><a href="mlr-t.html#every-coefficient-is-an-estimate"><i class="fa fa-check"></i>Every coefficient is an estimate</a></li>
<li class="chapter" data-level="" data-path="mlr-t.html"><a href="mlr-t.html#the-test"><i class="fa fa-check"></i>The test</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="mlr-f.html"><a href="mlr-f.html"><i class="fa fa-check"></i><b>8.6</b> Testing several coefficients at once</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#why-separate-tests-fail"><i class="fa fa-check"></i>Why separate tests fail</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#the-restricted-and-unrestricted-models"><i class="fa fa-check"></i>The restricted and unrestricted models</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#building-the-statistic"><i class="fa fa-check"></i>Building the statistic</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#why-an-f-distribution"><i class="fa fa-check"></i>Why an F distribution</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#does-prior-record-belong-in-the-model"><i class="fa fa-check"></i>Does prior record belong in the model?</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#the-f-statistic-r-prints-by-itself"><i class="fa fa-check"></i>The F statistic R prints by itself</a></li>
<li class="chapter" data-level="" data-path="mlr-f.html"><a href="mlr-f.html#a-joint-test-that-does-not-reject"><i class="fa fa-check"></i>A joint test that does not reject</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="mlr-causal.html"><a href="mlr-causal.html"><i class="fa fa-check"></i><b>8.7</b> Does this give us causality?</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-causal.html"><a href="mlr-causal.html#where-bias-comes-from"><i class="fa fa-check"></i>Where bias comes from</a></li>
<li class="chapter" data-level="" data-path="mlr-causal.html"><a href="mlr-causal.html#checking-the-arithmetic"><i class="fa fa-check"></i>Checking the arithmetic</a></li>
<li class="chapter" data-level="" data-path="mlr-causal.html"><a href="mlr-causal.html#what-the-controls-did-and-did-not-do"><i class="fa fa-check"></i>What the controls did and did not do</a></li>
<li class="chapter" data-level="" data-path="mlr-causal.html"><a href="mlr-causal.html#the-other-three-ways-clrm4-fails"><i class="fa fa-check"></i>The other three ways CLRM4 fails</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="mlr-summary.html"><a href="mlr-summary.html"><i class="fa fa-check"></i><b>8.8</b> Summary</a></li>
<li class="chapter" data-level="8.9" data-path="mlr-practice.html"><a href="mlr-practice.html"><i class="fa fa-check"></i><b>8.9</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-practice.html"><a href="mlr-practice.html#numerical-problems-5"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="mlr-practice.html"><a href="mlr-practice.html#concept-checks-6"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="mlr-practice.html"><a href="mlr-practice.html#r-exercises-5"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="mlr-question-bank.html"><a href="mlr-question-bank.html"><i class="fa fa-check"></i><b>8.10</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="mlr-question-bank.html"><a href="mlr-question-bank.html#multiple-choice-7"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="mlr-question-bank.html"><a href="mlr-question-bank.html#short-reasoning-7"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="mlr-question-bank.html"><a href="mlr-question-bank.html#numerical-7"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="mlr-looking-ahead.html"><a href="mlr-looking-ahead.html"><i class="fa fa-check"></i><b>8.11</b> Looking ahead</a></li>
<li class="chapter" data-level="8.12" data-path="mlr-matrix-note.html"><a href="mlr-matrix-note.html"><i class="fa fa-check"></i><b>8.12</b> Mathematical note: multiple regression in matrix form</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="specification.html"><a href="specification.html"><i class="fa fa-check"></i><b>9</b> Which Model Should We Fit?</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ff-motivation.html"><a href="ff-motivation.html"><i class="fa fa-check"></i><b>9.1</b> Is a straight line the right model?</a></li>
<li class="chapter" data-level="9.2" data-path="ff-four.html"><a href="ff-four.html"><i class="fa fa-check"></i><b>9.2</b> The four functional forms</a></li>
<li class="chapter" data-level="9.3" data-path="ff-elasticity.html"><a href="ff-elasticity.html"><i class="fa fa-check"></i><b>9.3</b> Elasticities: weight and fuel efficiency</a></li>
<li class="chapter" data-level="9.4" data-path="ff-schooling.html"><a href="ff-schooling.html"><i class="fa fa-check"></i><b>9.4</b> Percentages: the return to schooling</a></li>
<li class="chapter" data-level="9.5" data-path="ff-hetero.html"><a href="ff-hetero.html"><i class="fa fa-check"></i><b>9.5</b> When logs remove what looked like heteroskedasticity</a></li>
<li class="chapter" data-level="9.6" data-path="ff-choosing.html"><a href="ff-choosing.html"><i class="fa fa-check"></i><b>9.6</b> Choosing a form</a></li>
<li class="chapter" data-level="9.7" data-path="ff-irrelevant.html"><a href="ff-irrelevant.html"><i class="fa fa-check"></i><b>9.7</b> Does adding a variable ever cost anything?</a></li>
<li class="chapter" data-level="9.8" data-path="ff-adjr2.html"><a href="ff-adjr2.html"><i class="fa fa-check"></i><b>9.8</b> R-squared always rises</a>
<ul>
<li class="chapter" data-level="" data-path="ff-adjr2.html"><a href="ff-adjr2.html#adjusted-r-squared"><i class="fa fa-check"></i>Adjusted R-squared</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="ff-r2-limits.html"><a href="ff-r2-limits.html"><i class="fa fa-check"></i><b>9.9</b> What R-squared cannot tell you</a></li>
<li class="chapter" data-level="9.10" data-path="ff-controls.html"><a href="ff-controls.html"><i class="fa fa-check"></i><b>9.10</b> Good controls and bad controls</a>
<ul>
<li class="chapter" data-level="" data-path="ff-controls.html"><a href="ff-controls.html#a-variable-that-causes-both"><i class="fa fa-check"></i>A variable that causes both</a></li>
<li class="chapter" data-level="" data-path="ff-controls.html"><a href="ff-controls.html#a-variable-that-x-causes"><i class="fa fa-check"></i>A variable that x causes</a></li>
<li class="chapter" data-level="" data-path="ff-controls.html"><a href="ff-controls.html#a-variable-that-both-x-and-the-error-cause"><i class="fa fa-check"></i>A variable that both x and the error cause</a></li>
<li class="chapter" data-level="" data-path="ff-controls.html"><a href="ff-controls.html#what-this-means-in-practice"><i class="fa fa-check"></i>What this means in practice</a></li>
</ul></li>
<li class="chapter" data-level="9.11" data-path="ff-summary.html"><a href="ff-summary.html"><i class="fa fa-check"></i><b>9.11</b> Summary</a></li>
<li class="chapter" data-level="9.12" data-path="ff-practice.html"><a href="ff-practice.html"><i class="fa fa-check"></i><b>9.12</b> Practice problems</a>
<ul>
<li class="chapter" data-level="" data-path="ff-practice.html"><a href="ff-practice.html#numerical-problems-6"><i class="fa fa-check"></i>Numerical problems</a></li>
<li class="chapter" data-level="" data-path="ff-practice.html"><a href="ff-practice.html#concept-checks-7"><i class="fa fa-check"></i>Concept checks</a></li>
<li class="chapter" data-level="" data-path="ff-practice.html"><a href="ff-practice.html#r-exercises-6"><i class="fa fa-check"></i>R exercises</a></li>
</ul></li>
<li class="chapter" data-level="9.13" data-path="ff-question-bank.html"><a href="ff-question-bank.html"><i class="fa fa-check"></i><b>9.13</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="ff-question-bank.html"><a href="ff-question-bank.html#multiple-choice-8"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="ff-question-bank.html"><a href="ff-question-bank.html#short-reasoning-8"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="ff-question-bank.html"><a href="ff-question-bank.html#numerical-8"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="9.14" data-path="ff-looking-ahead.html"><a href="ff-looking-ahead.html"><i class="fa fa-check"></i><b>9.14</b> Looking ahead</a></li>
</ul></li>
<li class="divider"></li>
<li class="toc-after">Kedar Kulkarni · Azim Premji University<br>
<a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics and Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ts-practice" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Practice problems<a href="ts-practice.html#ts-practice" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="yourturn">
<p>Work each one before opening the solution. The
<a href="ts-question-bank.html#ts-question-bank">question bank</a> that follows has no answers.</p>
</div>
<div id="concept-checks-3" class="section level3 unnumbered hasAnchor">
<h3>Concept checks<a href="ts-practice.html#concept-checks-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>5.1</strong> Why is the standard error of a difference of means larger than the
standard error of either mean on its own?</p>
<div class="answer">
<p>Because the two sample means each carry sampling variation, and both end up in
the difference. Formally, <span class="math inline">\(\mathrm{Var}(aX) = a^2\mathrm{Var}(X)\)</span> with <span class="math inline">\(a = -1\)</span>
gives <span class="math inline">\((-1)^2 = +1\)</span>, so the variances add:</p>
<p><span class="math display">\[\mathrm{Var}[\bar{X} - \bar{Y}] = \frac{\sigma_x^2}{n} + \frac{\sigma_y^2}{m}\]</span></p>
<p>Subtracting a noisy quantity does not cancel noise; it adds more. This is why
detecting a difference between two groups takes more data than estimating one
group’s mean to the same precision.</p>
</div>
<p><strong>5.2</strong> A study reports that two groups differ with <span class="math inline">\(p = 0.003\)</span>. A colleague
concludes the difference is large. What is wrong?</p>
<div class="answer">
<p>The <span class="math inline">\(p\)</span>-value measures how incompatible the data are with the claim of no
difference. It says nothing about the size of the difference.</p>
<p>A very small <span class="math inline">\(p\)</span>-value can come from a tiny difference measured in a large
sample. The size of the difference is reported by the confidence interval, in
the units of the problem, and that is what has to be inspected before calling a
result large or important.</p>
</div>
<p><strong>5.3</strong> Why does R’s <code>t.test()</code> report fractional degrees of freedom?</p>
<div class="answer">
<p>Because it performs Welch’s test by default, which does not assume the two
populations have equal variances. The correction for that extra uncertainty
adjusts the degrees of freedom downwards, and the adjustment is generally not a
whole number.</p>
<p>The pooled test, obtained with <code>var.equal = TRUE</code>, uses <span class="math inline">\(n + m - 2\)</span> degrees of
freedom, which always is.</p>
</div>
<p><strong>5.4</strong> The same twenty households are surveyed before and after a cash
transfer. Why is a two-sample test the wrong tool?</p>
<div class="answer">
<p>Because the two columns are not independent samples — each household appears in
both. The design produces one number per household, the change.</p>
<p>Households differ enormously among themselves, and that variation is present
identically in both columns. A two-sample test treats it as noise, and it
swamps the change we are trying to detect. Taking differences within households
removes it, leaving only the quantity of interest.</p>
</div>
<p><strong>5.5</strong> Villages that received a road show higher incomes than villages that
did not. State two distinct reasons this need not mean the road raised incomes.</p>
<div class="answer">
<p>First, the villages may have differed beforehand. Roads are not built at random
— they tend to reach places that are more accessible, more populous, more
politically connected or already better off. Those same features raise incomes
on their own.</p>
<p>Second, the two groups may differ in things that changed alongside the road:
electrification, a market, a school. The road is correlated with a bundle of
improvements, and a comparison of means attributes the whole bundle to it.</p>
<p>In both cases the arithmetic is correct and the causal reading is not.</p>
</div>
</div>
<div id="explain-3" class="section level3 unnumbered hasAnchor">
<h3>Explain<a href="ts-practice.html#explain-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>5.6</strong> Explain the trade-off between the pooled and Welch tests, and why
modern practice prefers Welch.</p>
<div class="answer">
<p>Pooling assumes the two populations share a standard deviation. If true, both
samples estimate the same quantity, they can be combined, and the resulting
test has <span class="math inline">\(n + m - 2\)</span> degrees of freedom — more than Welch allows, so more
power.</p>
<p>If false, the pooled estimate averages two different quantities and the test is
wrong in a way nothing in the output reveals. Welch avoids the assumption
entirely, at the cost of fewer degrees of freedom.</p>
<p>The reason to prefer Welch is asymmetric risk. When the variances really are
equal, Welch loses very little. When they are not, pooling misleads. And the
assumption cannot be verified — a test of equal variances can only fail to
reject, which is not the same as establishing it.</p>
</div>
<p><strong>5.7</strong> A researcher tests whether men and women in a firm are paid differently,
finds <span class="math inline">\(p = 0.02\)</span>, and concludes the firm discriminates. Evaluate.</p>
<div class="answer">
<p>The test establishes that average pay differs by more than sampling variation
would explain. That is not the same as discrimination.</p>
<p>Men and women in the firm may differ in role, seniority, years of experience,
hours, or field of training, and any of those could account for a pay gap
without anyone being treated differently for the same work. The comparison of
raw means attributes the whole difference to sex because sex is the only
variable in the analysis.</p>
<p>Establishing discrimination requires comparing like with like — people doing
the same work with the same experience — which is a question of design and, in
later units, of holding other variables constant. The two-sample test is not
capable of it.</p>
</div>
</div>
<div id="numerical-problems-3" class="section level3 unnumbered hasAnchor">
<h3>Numerical problems<a href="ts-practice.html#numerical-problems-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>5.8</strong> Two irrigation methods are trialled. Drip irrigation on 15 plots yields
a mean of 38.4 quintals per hectare; flood irrigation on 18 plots yields 35.9.
Population standard deviations are known to be 3.2 and 4.1 respectively.</p>
<ol style="list-style-type: lower-roman">
<li>Test at the 5% level whether the mean yields differ.</li>
<li>Construct a 95% confidence interval for the difference.</li>
<li>Does the interval agree with the test?</li>
</ol>
<div class="answer">
<p><strong>(i)</strong> The standard error of the difference is</p>
<p><span class="math display">\[\sqrt{\frac{3.2^2}{15} + \frac{4.1^2}{18}} = \sqrt{0.6827 + 0.9339}
= \sqrt{1.6166} = 1.271\]</span></p>
<p><span class="math display">\[Z_{calc} = \frac{38.4 - 35.9}{1.271} = \frac{2.5}{1.271} = 1.967\]</span></p>
<p>Since <span class="math inline">\(1.967 &gt; 1.96\)</span>, we reject <span class="math inline">\(H_0\)</span> at the 5% level — but only just.</p>
<p><strong>(ii)</strong> <span class="math inline">\(2.5 \pm 1.96(1.271) = 2.5 \pm 2.491 = [0.009,\ 4.991]\)</span>.</p>
<p><strong>(iii)</strong> Yes. The interval excludes zero, and the test rejects. Both do so by
the narrowest possible margin, which is the same fact stated twice: the interval
endpoint sits at 0.009 because <span class="math inline">\(Z_{calc}\)</span> sits at 1.967.</p>
<p>A result this marginal should be reported as marginal. Nothing about it
justifies confidence that drip irrigation is better.</p>
</div>
<p><strong>5.9</strong> Two samples give <span class="math inline">\(n = 10\)</span>, <span class="math inline">\(s_x = 4\)</span> and <span class="math inline">\(m = 14\)</span>, <span class="math inline">\(s_y = 6\)</span>.</p>
<ol style="list-style-type: lower-roman">
<li>Compute the pooled variance estimate.</li>
<li>How many degrees of freedom does the pooled test use?</li>
<li>Why is it not <span class="math inline">\(n + m\)</span>?</li>
</ol>
<div class="answer">
<p><strong>(i)</strong></p>
<p><span class="math display">\[s_p^2 = \frac{(10-1)16 + (14-1)36}{10 + 14 - 2}
= \frac{144 + 468}{22} = \frac{612}{22} = 27.82\]</span></p>
<p>so <span class="math inline">\(s_p = 5.27\)</span>, lying between 4 and 6 and closer to 6 because the larger
sample carries more weight.</p>
<p><strong>(ii)</strong> <span class="math inline">\(n + m - 2 = 22\)</span>.</p>
<p><strong>(iii)</strong> Because two quantities were estimated from the data before the spread
could be measured — one sample mean in each group. Each costs a degree of
freedom, exactly as in Section <a href="u3-variance.html#u3-variance">3.2</a>, where estimating a single
mean cost one.</p>
</div>
<p><strong>5.10</strong> A programme is evaluated by comparing 200 participants with 200
non-participants. Participants’ mean income is ₹4,200 higher, with a standard
error of ₹1,400 for the difference.</p>
<ol style="list-style-type: lower-roman">
<li>Test whether the difference is zero at the 5% level.</li>
<li>Construct a 95% interval.</li>
<li>The programme was open to anyone who applied. What can be concluded about
its effect?</li>
</ol>
<div class="answer">
<p><strong>(i)</strong> <span class="math inline">\(Z_{calc} = 4200/1400 = 3.0\)</span>, which exceeds 1.96. We reject the claim
that the two groups have the same mean income.</p>
<p><strong>(ii)</strong> <span class="math inline">\(4200 \pm 1.96(1400) = [₹1{,}456,\ ₹6{,}944]\)</span>.</p>
<p><strong>(iii)</strong> Nothing about its effect. Because the programme was open to
applicants, participants selected themselves. People who apply to income
programmes may be more motivated, better informed, or better connected — or,
equally plausibly, more desperate and worse off to begin with. The direction of
the bias is not even clear.</p>
<p>The interval is a correct statement about the difference between two groups of
people. It is not an estimate of what the programme did to anybody.</p>
</div>
</div>
<div id="r-exercises-3" class="section level3 unnumbered hasAnchor">
<h3>R exercises<a href="ts-practice.html#r-exercises-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>5.11</strong> Using <code>data/student-survey-sleep.csv</code>, test whether urban and rural
students report different average hours of sleep. Report the interval and say
what you conclude.</p>
<div class="answer">
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="ts-practice.html#cb213-1" tabindex="-1"></a>sleep <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/student-survey-sleep.csv&quot;</span>)</span>
<span id="cb213-2"><a href="ts-practice.html#cb213-2" tabindex="-1"></a></span>
<span id="cb213-3"><a href="ts-practice.html#cb213-3" tabindex="-1"></a><span class="fu">aggregate</span>(sleep <span class="sc">~</span> residence, <span class="at">data =</span> sleep,</span>
<span id="cb213-4"><a href="ts-practice.html#cb213-4" tabindex="-1"></a>          <span class="cf">function</span>(x) <span class="fu">round</span>(<span class="fu">c</span>(<span class="at">n =</span> <span class="fu">length</span>(x), <span class="at">mean =</span> <span class="fu">mean</span>(x), <span class="at">sd =</span> <span class="fu">sd</span>(x)), <span class="dv">2</span>))</span></code></pre></div>
<pre><code>#&gt;   residence sleep.n sleep.mean sleep.sd
#&gt; 1     Rural   21.00       6.52     1.53
#&gt; 2     Urban   85.00       6.60     1.12</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="ts-practice.html#cb215-1" tabindex="-1"></a><span class="fu">t.test</span>(sleep <span class="sc">~</span> residence, <span class="at">data =</span> sleep)</span></code></pre></div>
<pre><code>#&gt; 
#&gt;  Welch Two Sample t-test
#&gt; 
#&gt; data:  sleep by residence
#&gt; t = -0.21, df = 26, p-value = 0.8
#&gt; alternative hypothesis: true difference in means between group Rural and group Urban is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.8064  0.6540
#&gt; sample estimates:
#&gt; mean in group Rural mean in group Urban 
#&gt;               6.524               6.600</code></pre>
<p>The two group means are close and the interval for the difference contains
zero, so we fail to reject. There is no evidence here that urban and rural
students sleep different amounts on average.</p>
<p>Note what “no evidence of a difference” is not: evidence of no difference. With
these sample sizes, a real difference of well under an hour would be difficult
to detect at all, and the interval says as much by being wide.</p>
</div>
<p><strong>5.12</strong> Test whether social media use differs between North and South Indian
students in the same dataset, using both Welch and the pooled test. Do they
agree, and which would you report?</p>
<div class="answer">
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="ts-practice.html#cb217-1" tabindex="-1"></a><span class="fu">rbind</span>(</span>
<span id="cb217-2"><a href="ts-practice.html#cb217-2" tabindex="-1"></a>  <span class="at">welch  =</span> <span class="fu">unlist</span>(<span class="fu">t.test</span>(socialmediahours <span class="sc">~</span> region, <span class="at">data =</span> sleep)[<span class="fu">c</span>(<span class="st">&quot;statistic&quot;</span>, <span class="st">&quot;parameter&quot;</span>, <span class="st">&quot;p.value&quot;</span>)]),</span>
<span id="cb217-3"><a href="ts-practice.html#cb217-3" tabindex="-1"></a>  <span class="at">pooled =</span> <span class="fu">unlist</span>(<span class="fu">t.test</span>(socialmediahours <span class="sc">~</span> region, <span class="at">data =</span> sleep, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)[<span class="fu">c</span>(<span class="st">&quot;statistic&quot;</span>, <span class="st">&quot;parameter&quot;</span>, <span class="st">&quot;p.value&quot;</span>)])</span>
<span id="cb217-4"><a href="ts-practice.html#cb217-4" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>#&gt;        statistic.t parameter.df p.value
#&gt; welch       0.9172        50.63  0.3634
#&gt; pooled      0.9845       104.00  0.3271</code></pre>
<p>The two agree closely here, which is what happens when the sample standard
deviations are similar — the pooled and separate estimates of the variance are
then nearly the same number.</p>
<p>Report Welch. It gives the same answer when the assumption holds and a correct
one when it does not, so there is no situation in which pooling is the safer
choice.</p>
</div>
<p><strong>5.13</strong> Take the wage data as a population and draw independent samples of 200
urban and 200 rural workers. Test whether mean annual earnings differ, and
report the interval. Then say what the interval does and does not establish.</p>
<div class="answer">
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="ts-practice.html#cb219-1" tabindex="-1"></a>wages <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/wages-india-synthetic.csv&quot;</span>)</span>
<span id="cb219-2"><a href="ts-practice.html#cb219-2" tabindex="-1"></a></span>
<span id="cb219-3"><a href="ts-practice.html#cb219-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">9</span>)</span>
<span id="cb219-4"><a href="ts-practice.html#cb219-4" tabindex="-1"></a>urban <span class="ot">&lt;-</span> <span class="fu">sample</span>(wages<span class="sc">$</span>annual_earnings[wages<span class="sc">$</span>residence <span class="sc">==</span> <span class="st">&quot;Urban&quot;</span>], <span class="dv">200</span>)</span>
<span id="cb219-5"><a href="ts-practice.html#cb219-5" tabindex="-1"></a>rural <span class="ot">&lt;-</span> <span class="fu">sample</span>(wages<span class="sc">$</span>annual_earnings[wages<span class="sc">$</span>residence <span class="sc">==</span> <span class="st">&quot;Rural&quot;</span>], <span class="dv">200</span>)</span>
<span id="cb219-6"><a href="ts-practice.html#cb219-6" tabindex="-1"></a></span>
<span id="cb219-7"><a href="ts-practice.html#cb219-7" tabindex="-1"></a><span class="fu">t.test</span>(urban, rural)</span></code></pre></div>
<pre><code>#&gt; 
#&gt;  Welch Two Sample t-test
#&gt; 
#&gt; data:  urban and rural
#&gt; t = 6.5, df = 223, p-value = 0.0000000005
#&gt; alternative hypothesis: true difference in means is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  47095 88103
#&gt; sample estimates:
#&gt; mean of x mean of y 
#&gt;    100811     33212</code></pre>
<p>The difference is large and the interval is nowhere near zero, so urban workers
in this population earn substantially more than rural workers.</p>
<p>What the interval establishes is the size of that gap. What it does not
establish is that moving a worker from a village to a city would raise their
earnings by that amount. Urban and rural workers differ in education,
occupation and industry, and the sample says nothing about which part of the gap
belongs to the place and which to the people.</p>
</div>
<p><strong>5.14</strong> Simulate the point that variances add. Draw two independent samples of
100 from a population with <span class="math inline">\(\sigma = 10\)</span>, and compare the observed standard
deviation of <span class="math inline">\(\bar{x}\)</span> with that of <span class="math inline">\(\bar{x} - \bar{y}\)</span> across 5,000
repetitions. Check both against theory.</p>
<div class="answer">
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="ts-practice.html#cb221-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">4</span>)</span>
<span id="cb221-2"><a href="ts-practice.html#cb221-2" tabindex="-1"></a>sims <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">5000</span>, {</span>
<span id="cb221-3"><a href="ts-practice.html#cb221-3" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb221-4"><a href="ts-practice.html#cb221-4" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="at">mean =</span> <span class="dv">50</span>, <span class="at">sd =</span> <span class="dv">10</span>)</span>
<span id="cb221-5"><a href="ts-practice.html#cb221-5" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">one_mean =</span> <span class="fu">mean</span>(x), <span class="at">difference =</span> <span class="fu">mean</span>(x) <span class="sc">-</span> <span class="fu">mean</span>(y))</span>
<span id="cb221-6"><a href="ts-practice.html#cb221-6" tabindex="-1"></a>})</span>
<span id="cb221-7"><a href="ts-practice.html#cb221-7" tabindex="-1"></a></span>
<span id="cb221-8"><a href="ts-practice.html#cb221-8" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sd_of_one_mean       =</span> <span class="fu">sd</span>(sims[<span class="st">&quot;one_mean&quot;</span>, ]),</span>
<span id="cb221-9"><a href="ts-practice.html#cb221-9" tabindex="-1"></a>        <span class="at">theory_one_mean      =</span> <span class="dv">10</span> <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>),</span>
<span id="cb221-10"><a href="ts-practice.html#cb221-10" tabindex="-1"></a>        <span class="at">sd_of_difference     =</span> <span class="fu">sd</span>(sims[<span class="st">&quot;difference&quot;</span>, ]),</span>
<span id="cb221-11"><a href="ts-practice.html#cb221-11" tabindex="-1"></a>        <span class="at">theory_difference    =</span> <span class="fu">sqrt</span>(<span class="dv">10</span><span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">100</span> <span class="sc">+</span> <span class="dv">10</span><span class="sc">^</span><span class="dv">2</span><span class="sc">/</span><span class="dv">100</span>)), <span class="dv">4</span>)</span></code></pre></div>
<pre><code>#&gt;    sd_of_one_mean   theory_one_mean  sd_of_difference theory_difference 
#&gt;            0.9989            1.0000            1.4260            1.4142</code></pre>
<p>The difference is about <span class="math inline">\(\sqrt{2}\)</span> times as variable as a single mean, exactly
as <span class="math inline">\(\sqrt{\sigma^2/n + \sigma^2/m}\)</span> predicts. Note also that the difference is
centred on zero: both populations have mean 50, and the estimator is unbiased
for a difference of zero.</p>
</div>
<p><strong>5.15</strong> Demonstrate the cost of ignoring pairing. Using <code>marriage-ages.csv</code>,
report the paired and unpaired <span class="math inline">\(p\)</span>-values, and explain the gap by comparing the
standard deviation of the differences with the standard deviations of the two
columns.</p>
<div class="answer">
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="ts-practice.html#cb223-1" tabindex="-1"></a>couples <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/marriage-ages.csv&quot;</span>)</span>
<span id="cb223-2"><a href="ts-practice.html#cb223-2" tabindex="-1"></a></span>
<span id="cb223-3"><a href="ts-practice.html#cb223-3" tabindex="-1"></a><span class="fu">c</span>(<span class="at">paired   =</span> <span class="fu">t.test</span>(couples<span class="sc">$</span>partner1, couples<span class="sc">$</span>partner2, <span class="at">paired =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>p.value,</span>
<span id="cb223-4"><a href="ts-practice.html#cb223-4" tabindex="-1"></a>  <span class="at">unpaired =</span> <span class="fu">t.test</span>(couples<span class="sc">$</span>partner1, couples<span class="sc">$</span>partner2)<span class="sc">$</span>p.value)</span></code></pre></div>
<pre><code>#&gt;   paired unpaired 
#&gt;  0.01496  0.60699</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="ts-practice.html#cb225-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">sd_partner1  =</span> <span class="fu">sd</span>(couples<span class="sc">$</span>partner1),</span>
<span id="cb225-2"><a href="ts-practice.html#cb225-2" tabindex="-1"></a>        <span class="at">sd_partner2  =</span> <span class="fu">sd</span>(couples<span class="sc">$</span>partner2),</span>
<span id="cb225-3"><a href="ts-practice.html#cb225-3" tabindex="-1"></a>        <span class="at">sd_of_diffs  =</span> <span class="fu">sd</span>(couples<span class="sc">$</span>partner1 <span class="sc">-</span> couples<span class="sc">$</span>partner2)), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>#&gt; sd_partner1 sd_partner2 sd_of_diffs 
#&gt;      11.156      10.174       2.635</code></pre>
<p>The two columns each have a standard deviation of about 11 years, because the
couples range from their mid-thirties to their seventies. The differences have a
standard deviation of about 2.6 years.</p>
<p>That is the whole explanation. The unpaired test measures the small gap against
the huge between-couple variation and sees nothing. The paired test removes that
variation — it is common to both columns and cancels on subtraction — and
measures the gap against what is left.</p>
</div>
</div>
<div id="paired-designs" class="section level3 unnumbered hasAnchor">
<h3>Paired designs<a href="ts-practice.html#paired-designs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>5.16</strong> A paired test on <span class="math inline">\(n\)</span> pairs has <span class="math inline">\(n - 1\)</span> degrees of freedom, not
<span class="math inline">\(2n - 2\)</span>. Why, when there are <span class="math inline">\(2n\)</span> numbers in the dataset?</p>
<div class="answer">
<p>Because the analysis is not performed on the <span class="math inline">\(2n\)</span> numbers. It is performed on
the <span class="math inline">\(n\)</span> differences.</p>
<p>Taking differences reduces <span class="math inline">\(2n\)</span> observations to <span class="math inline">\(n\)</span>, one per pair. From those
<span class="math inline">\(n\)</span> we estimate one quantity, <span class="math inline">\(\bar{d}\)</span>, before we can measure their spread, so
one degree of freedom is spent and <span class="math inline">\(n - 1\)</span> remain — exactly as in the one-sample
case of Section <a href="u3-variance.html#u3-variance">3.2</a>.</p>
<p>The <span class="math inline">\(2n - 2\)</span> of the pooled two-sample test is right for a design in which the
<span class="math inline">\(2n\)</span> observations really are <span class="math inline">\(2n\)</span> independent pieces of information. In a paired
design they are not: knowing one member of a pair tells you a great deal about
the other.</p>
</div>
<p><strong>5.17</strong> What feature of the data determines whether pairing was worth doing?</p>
<div class="answer">
<p>The correlation between the two columns.</p>
<p>Pairing removes whatever is common to both members of a pair. If the two
measurements are strongly related — the same household in two rounds, the same
plot in two seasons — then a great deal is common, differencing removes it, and
the standard error falls sharply.</p>
<p>If the two columns happen to be unrelated, there is nothing common to remove.
Differencing then leaves the variability essentially unchanged, and the paired
test performs about as well as the unpaired one, losing only the few degrees of
freedom.</p>
<p>So pairing rarely costs much and can gain a great deal. What determines which
happens is not a choice; it is a property of the design.</p>
</div>
<p><strong>5.18</strong> A researcher measures productivity at the same 30 firms before and
after a policy change, then runs a two-sample <span class="math inline">\(t\)</span>-test. Describe what will
happen to the <span class="math inline">\(p\)</span>-value and why.</p>
<div class="answer">
<p>It will be too large — often dramatically so — and the researcher will
under-report a real effect.</p>
<p>Firms differ enormously among themselves in productivity: a large firm and a
small one may differ by a factor of ten, while the policy might move any single
firm by a few per cent. In a two-sample test that between-firm variation is
counted as noise, and it swamps the change being looked for.</p>
<p>The pairing is exactly what removes it. Each firm’s before-measurement acts as
its own comparison, so the firm’s general productivity level cancels and only
its change remains. Writing <span class="math inline">\(x_i = \mu + \alpha_i + \delta_i\)</span> and
<span class="math inline">\(y_i = \mu + \alpha_i + \varepsilon_i\)</span>, the large firm effect <span class="math inline">\(\alpha_i\)</span> appears
in both and disappears on subtraction.</p>
<p>The error is conservative rather than anti-conservative, which is why it often
goes unnoticed: the researcher simply concludes there is no effect.</p>
</div>
<p><strong>5.19</strong> A new irrigation technique is trialled on eight plots. Yields in
quintals per hectare before and after are</p>
<table>
<thead>
<tr class="header">
<th align="left">Plot</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left">5</th>
<th align="left">6</th>
<th align="left">7</th>
<th align="left">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Before</td>
<td align="left">32</td>
<td align="left">28</td>
<td align="left">35</td>
<td align="left">30</td>
<td align="left">33</td>
<td align="left">29</td>
<td align="left">31</td>
<td align="left">34</td>
</tr>
<tr class="even">
<td align="left">After</td>
<td align="left">35</td>
<td align="left">33</td>
<td align="left">37</td>
<td align="left">36</td>
<td align="left">37</td>
<td align="left">30</td>
<td align="left">36</td>
<td align="left">40</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-roman">
<li>Explain why this is a paired design.</li>
<li>Compute the differences, <span class="math inline">\(\bar{d}\)</span> and <span class="math inline">\(s_d\)</span>.</li>
<li>Test at the 5% level whether the technique changed yields.</li>
<li>Construct a 95% confidence interval for the mean change.</li>
</ol>
<div class="answer">
<p><strong>(i)</strong> Each plot is measured twice. The two columns are not eight plots and
eight other plots; they are the same eight plots under two conditions, so every
observation in one column has a natural partner in the other. Plots differ in
soil, slope and drainage, and those differences are present identically in both
rounds.</p>
<p><strong>(ii)</strong> Differences (after <span class="math inline">\(-\)</span> before): <span class="math inline">\(3, 5, 2, 6, 4, 1, 5, 6\)</span>.</p>
<p><span class="math display">\[\bar{d} = \frac{32}{8} = 4.0\]</span></p>
<p>Deviations from 4: <span class="math inline">\(-1, 1, -2, 2, 0, -3, 1, 2\)</span>, whose squares sum to 24, so</p>
<p><span class="math display">\[s_d^2 = \frac{24}{7} = 3.4286 \qquad s_d = 1.852\]</span></p>
<p>and the standard error is <span class="math inline">\(1.852/\sqrt{8} = 0.655\)</span>.</p>
<p><strong>(iii)</strong></p>
<p><span class="math display">\[t = \frac{4.0}{0.655} = 6.11\]</span></p>
<p>with <span class="math inline">\(df = 7\)</span>. The critical value is <span class="math inline">\(t_{0.025,\,7} = 2.365\)</span>, and
<span class="math inline">\(6.11 &gt; 2.365\)</span>, so we reject <span class="math inline">\(H_0: \mu_d = 0\)</span>. The <span class="math inline">\(p\)</span>-value is 0.0005.</p>
<p><strong>(iv)</strong> <span class="math inline">\(4.0 \pm 2.365(0.655) = [2.45,\ 5.55]\)</span> quintals per hectare.</p>
<p>Note the interval is in the units of the problem and excludes zero, agreeing
with the test. Note also that the estimated gain of 4 quintals per hectare is
large in agronomic terms as well as statistically detectable — the two
questions are separate, and here both answers happen to be favourable.</p>
</div>
<p><strong>5.20</strong> Seven workers are timed on a task, in minutes, before and after
training.</p>
<table>
<thead>
<tr class="header">
<th align="left">Worker</th>
<th align="left">1</th>
<th align="left">2</th>
<th align="left">3</th>
<th align="left">4</th>
<th align="left">5</th>
<th align="left">6</th>
<th align="left">7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Before</td>
<td align="left">14</td>
<td align="left">12</td>
<td align="left">15</td>
<td align="left">13</td>
<td align="left">16</td>
<td align="left">11</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">After</td>
<td align="left">11</td>
<td align="left">10</td>
<td align="left">13</td>
<td align="left">12</td>
<td align="left">13</td>
<td align="left">11</td>
<td align="left">12</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: lower-roman">
<li>State the hypotheses for a test that training <em>reduced</em> completion time.</li>
<li>Compute the test statistic and its degrees of freedom.</li>
<li>Test at the 5% level.</li>
<li>Construct the appropriate one-sided 95% bound and interpret it.</li>
</ol>
<div class="answer">
<p><strong>(i)</strong> Working with <span class="math inline">\(d_i = \text{before}_i - \text{after}_i\)</span>, so that a
reduction in time gives a positive difference:</p>
<p><span class="math display">\[H_0 : \mu_d \leq 0 \qquad H_A : \mu_d &gt; 0\]</span></p>
<p>The equality lives in <span class="math inline">\(H_0\)</span>, as always, and the claim we want evidence <em>for</em>
sits in <span class="math inline">\(H_A\)</span>.</p>
<p><strong>(ii)</strong> Differences: <span class="math inline">\(3, 2, 2, 1, 3, 0, 2\)</span>. So <span class="math inline">\(\bar{d} = 13/7 = 1.857\)</span> and
<span class="math inline">\(s_d = 1.069\)</span>, giving a standard error of <span class="math inline">\(1.069/\sqrt{7} = 0.404\)</span> and</p>
<p><span class="math display">\[t = \frac{1.857}{0.404} = 4.60\]</span></p>
<p>with <span class="math inline">\(df = 6\)</span>.</p>
<p><strong>(iii)</strong> Right-tailed at 5%, so the critical value is <span class="math inline">\(t_{0.05,\,6} = 1.943\)</span> —
not 2.447. Since <span class="math inline">\(4.60 &gt; 1.943\)</span> we reject <span class="math inline">\(H_0\)</span>; the one-sided <span class="math inline">\(p\)</span>-value is
0.0019.</p>
<p><strong>(iv)</strong> A one-sided lower bound spends all of <span class="math inline">\(\alpha\)</span> in one tail:</p>
<p><span class="math display">\[\bar{d} - t_{0.05,\,6}\,\frac{s_d}{\sqrt{n}} = 1.857 - 1.943(0.404) = 1.07\]</span></p>
<p>so the interval is <span class="math inline">\([1.07,\ \infty)\)</span>. With 95% confidence, training reduced
completion time by at least 1.07 minutes. We have deliberately given up any
statement about how large the reduction might be, because the question only
asked whether there was one.</p>
</div>
<p><strong>5.21</strong> Using <code>marriage-ages.csv</code>, verify by direct computation that
<code>paired = TRUE</code> does nothing more than take differences. Then run the one-sided
test of whether partner 1 is older.</p>
<div class="answer">
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="ts-practice.html#cb227-1" tabindex="-1"></a>couples <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/marriage-ages.csv&quot;</span>)</span>
<span id="cb227-2"><a href="ts-practice.html#cb227-2" tabindex="-1"></a>d <span class="ot">&lt;-</span> couples<span class="sc">$</span>partner1 <span class="sc">-</span> couples<span class="sc">$</span>partner2</span>
<span id="cb227-3"><a href="ts-practice.html#cb227-3" tabindex="-1"></a></span>
<span id="cb227-4"><a href="ts-practice.html#cb227-4" tabindex="-1"></a><span class="co"># Three routes to the same number</span></span>
<span id="cb227-5"><a href="ts-practice.html#cb227-5" tabindex="-1"></a><span class="fu">c</span>(<span class="at">by_hand   =</span> <span class="fu">mean</span>(d) <span class="sc">/</span> (<span class="fu">sd</span>(d) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(d))),</span>
<span id="cb227-6"><a href="ts-practice.html#cb227-6" tabindex="-1"></a>  <span class="at">one_sample =</span> <span class="fu">t.test</span>(d, <span class="at">mu =</span> <span class="dv">0</span>)<span class="sc">$</span>statistic,</span>
<span id="cb227-7"><a href="ts-practice.html#cb227-7" tabindex="-1"></a>  <span class="at">paired     =</span> <span class="fu">t.test</span>(couples<span class="sc">$</span>partner1, couples<span class="sc">$</span>partner2, <span class="at">paired =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>statistic)</span></code></pre></div>
<pre><code>#&gt;      by_hand one_sample.t     paired.t 
#&gt;            3            3            3</code></pre>
<p>Identical, as they must be: <code>paired = TRUE</code> subtracts the columns and calls the
one-sample routine.</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="ts-practice.html#cb229-1" tabindex="-1"></a><span class="fu">t.test</span>(couples<span class="sc">$</span>partner1, couples<span class="sc">$</span>partner2,</span>
<span id="cb229-2"><a href="ts-practice.html#cb229-2" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; 
#&gt;  Paired t-test
#&gt; 
#&gt; data:  couples$partner1 and couples$partner2
#&gt; t = 3, df = 9, p-value = 0.007
#&gt; alternative hypothesis: true mean difference is greater than 0
#&gt; 95 percent confidence interval:
#&gt;  0.9724    Inf
#&gt; sample estimates:
#&gt; mean difference 
#&gt;             2.5</code></pre>
<p>The one-sided <span class="math inline">\(p\)</span>-value is half the two-sided one, 0.0075 against 0.015, and the
interval is now a lower bound: partner 1 is older by at least 1.02 years.</p>
<p>The one-sided test is defensible here only because the direction was decided
before looking — we asked whether partner 1 is older, not whether the two
differ. Choosing the direction after seeing that eight of ten differences were
positive would not be a test at all.</p>
</div>
<p><strong>5.22</strong> Show that the benefit of pairing depends on the correlation between the
two columns. Simulate pairs of measurements with correlation 0, 0.5 and 0.9, a
true difference of 4, and <span class="math inline">\(n = 10\)</span>, and compare how often each test rejects.</p>
<div class="answer">
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="ts-practice.html#cb231-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">7</span>)</span>
<span id="cb231-2"><a href="ts-practice.html#cb231-2" tabindex="-1"></a></span>
<span id="cb231-3"><a href="ts-practice.html#cb231-3" tabindex="-1"></a>power_at <span class="ot">&lt;-</span> <span class="cf">function</span>(rho, <span class="at">reps =</span> <span class="dv">4000</span>) {</span>
<span id="cb231-4"><a href="ts-practice.html#cb231-4" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">replicate</span>(reps, {</span>
<span id="cb231-5"><a href="ts-practice.html#cb231-5" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb231-6"><a href="ts-practice.html#cb231-6" tabindex="-1"></a>    b <span class="ot">&lt;-</span> rho <span class="sc">*</span> a <span class="sc">+</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">-</span> rho<span class="sc">^</span><span class="dv">2</span>) <span class="sc">*</span> <span class="fu">rnorm</span>(<span class="dv">10</span>)</span>
<span id="cb231-7"><a href="ts-practice.html#cb231-7" tabindex="-1"></a>    x <span class="ot">&lt;-</span> <span class="dv">50</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> a</span>
<span id="cb231-8"><a href="ts-practice.html#cb231-8" tabindex="-1"></a>    y <span class="ot">&lt;-</span> <span class="dv">50</span> <span class="sc">+</span> <span class="dv">10</span> <span class="sc">*</span> b <span class="sc">+</span> <span class="dv">4</span>                       <span class="co"># true difference is 4</span></span>
<span id="cb231-9"><a href="ts-practice.html#cb231-9" tabindex="-1"></a>    <span class="fu">c</span>(<span class="at">paired   =</span> <span class="fu">t.test</span>(x, y, <span class="at">paired =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb231-10"><a href="ts-practice.html#cb231-10" tabindex="-1"></a>      <span class="at">unpaired =</span> <span class="fu">t.test</span>(x, y)<span class="sc">$</span>p.value           <span class="sc">&lt;</span> <span class="fl">0.05</span>,</span>
<span id="cb231-11"><a href="ts-practice.html#cb231-11" tabindex="-1"></a>      <span class="at">se_paired   =</span> <span class="fu">sd</span>(x <span class="sc">-</span> y) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">10</span>),</span>
<span id="cb231-12"><a href="ts-practice.html#cb231-12" tabindex="-1"></a>      <span class="at">se_unpaired =</span> <span class="fu">sqrt</span>(<span class="fu">var</span>(x)<span class="sc">/</span><span class="dv">10</span> <span class="sc">+</span> <span class="fu">var</span>(y)<span class="sc">/</span><span class="dv">10</span>))</span>
<span id="cb231-13"><a href="ts-practice.html#cb231-13" tabindex="-1"></a>  })</span>
<span id="cb231-14"><a href="ts-practice.html#cb231-14" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">rho =</span> rho, <span class="fu">rowMeans</span>(out))</span>
<span id="cb231-15"><a href="ts-practice.html#cb231-15" tabindex="-1"></a>}</span>
<span id="cb231-16"><a href="ts-practice.html#cb231-16" tabindex="-1"></a></span>
<span id="cb231-17"><a href="ts-practice.html#cb231-17" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">t</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="fl">0.9</span>), power_at)), <span class="dv">3</span>)</span></code></pre></div>
<pre><code>#&gt;      rho paired unpaired se_paired se_unpaired
#&gt; [1,] 0.0  0.125    0.126     4.348       4.408
#&gt; [2,] 0.5  0.212    0.073     3.069       4.402
#&gt; [3,] 0.9  0.717    0.014     1.374       4.389</code></pre>
<p>Read the two standard error columns first, because they explain everything else.
The paired standard error falls from about 4.35 to 1.37 as the correlation
rises. The unpaired standard error sits near 4.40 throughout — it is computed
from the two columns separately and so cannot notice that they are related at
all.</p>
<p>The rejection rates follow. At <span class="math inline">\(\rho = 0\)</span> the two tests are equivalent, and the
paired one is marginally worse because it has 9 degrees of freedom against 18.
At <span class="math inline">\(\rho = 0.9\)</span> the paired test rejects about 72% of the time and the unpaired
test almost never does.</p>
<p>That last figure deserves a moment. The unpaired test does not merely fail to
improve as the correlation rises; it gets <em>worse</em>. With strongly correlated
columns the observed difference is tightly concentrated near its true value of
4, while the standard error the unpaired test uses stays at 4.4 — so its
statistic sits reliably near <span class="math inline">\(4/4.4 \approx 0.9\)</span> and almost never strays past
the critical value. Ignoring a strong pairing produces a test that is
consistently, confidently unable to see anything.</p>
</div>
</div>
</div>
<script>
// Solutions are written as plain fenced divs in the source, so the PDF edition
// can typeset them as boxes. On the web they should stay hidden until asked
// for, so wrap each one in a <details> here.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll("div.answer").forEach(function (div) {
    var d = document.createElement("details");
    d.className = "answer";
    var s = document.createElement("summary");
    s.textContent = "Show the solution";
    d.appendChild(s);
    while (div.firstChild) d.appendChild(div.firstChild);
    div.parentNode.replaceChild(d, div);
  });
});
</script>
            </section>

          </div>
        </div>
      </div>
<a href="ts-summary.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ts-question-bank.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/kedarkulkarni1991/stats-econometrics-r/edit/main/05-two-sample.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["stats-econometrics-r.pdf"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
