<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.5 Why do larger samples give more reliable answers? | Statistics and Econometrics with R</title>
  <meta name="description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="1.5 Why do larger samples give more reliable answers? | Statistics and Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  <meta name="github-repo" content="kedarkulkarni1991/stats-econometrics-r" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.5 Why do larger samples give more reliable answers? | Statistics and Econometrics with R" />
  
  <meta name="twitter:description" content="<p>A first course in statistics and econometrics for Indian students, built on
the progression from question to intuition to rigour to computation to
interpretation.</p>" />
  

<meta name="author" content="Kedar Kulkarni" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="u1-frequentist.html"/>
<link rel="next" href="u1-clt.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><strong>Statistics &amp; Econometrics with R</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i>How to use this book</a>
<ul>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-the-book-in-order"><i class="fa fa-check"></i>Read the book in order</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#work-through-the-mathematics"><i class="fa fa-check"></i>Work through the mathematics</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#think-in-words-before-thinking-in-mathematics"><i class="fa fa-check"></i>Think in words before thinking in mathematics</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#write-the-code-yourself"><i class="fa fa-check"></i>Write the code yourself</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#think-before-calculating"><i class="fa fa-check"></i>Think before calculating</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#attempt-the-exercises-first"><i class="fa fa-check"></i>Attempt the exercises first</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#use-the-book-as-a-reference"><i class="fa fa-check"></i>Use the book as a reference</a></li>
<li class="chapter" data-level="" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#learn-by-connecting-ideas"><i class="fa fa-check"></i>Learn by connecting ideas</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="what-you-need.html"><a href="what-you-need.html"><i class="fa fa-check"></i>What you need</a></li>
<li class="chapter" data-level="" data-path="notation-used-throughout.html"><a href="notation-used-throughout.html"><i class="fa fa-check"></i>Notation used throughout</a></li>
<li class="chapter" data-level="" data-path="a-note-on-the-data.html"><a href="a-note-on-the-data.html"><i class="fa fa-check"></i>A note on the data</a></li>
<li class="chapter" data-level="" data-path="licence-and-citation.html"><a href="licence-and-citation.html"><i class="fa fa-check"></i>Licence and citation</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="towards-inference.html"><a href="towards-inference.html"><i class="fa fa-check"></i><b>1</b> Towards Inferential Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="u1-randomness.html"><a href="u1-randomness.html"><i class="fa fa-check"></i><b>1.1</b> Randomness and variation</a></li>
<li class="chapter" data-level="1.2" data-path="u1-describing.html"><a href="u1-describing.html"><i class="fa fa-check"></i><b>1.2</b> Describing variation</a></li>
<li class="chapter" data-level="1.3" data-path="u1-not-enough.html"><a href="u1-not-enough.html"><i class="fa fa-check"></i><b>1.3</b> The limits of descriptive statistics</a></li>
<li class="chapter" data-level="1.4" data-path="u1-frequentist.html"><a href="u1-frequentist.html"><i class="fa fa-check"></i><b>1.4</b> What if we repeated the survey?</a></li>
<li class="chapter" data-level="1.5" data-path="u1-lln.html"><a href="u1-lln.html"><i class="fa fa-check"></i><b>1.5</b> Why do larger samples give more reliable answers?</a></li>
<li class="chapter" data-level="1.6" data-path="u1-clt.html"><a href="u1-clt.html"><i class="fa fa-check"></i><b>1.6</b> The Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#a-simulation"><i class="fa fa-check"></i>A simulation</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#an-intuition"><i class="fa fa-check"></i>An intuition</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#how-large-is-large-enough"><i class="fa fa-check"></i>How large is “large enough”?</a></li>
<li class="chapter" data-level="" data-path="u1-clt.html"><a href="u1-clt.html#why-this-matters"><i class="fa fa-check"></i>Why this matters</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="u1-random-variables.html"><a href="u1-random-variables.html"><i class="fa fa-check"></i><b>1.7</b> A language for randomness</a>
<ul>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#the-long-run-average"><i class="fa fa-check"></i>The long-run average</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#population-and-sample-in-notation"><i class="fa fa-check"></i>Population and sample, in notation</a></li>
<li class="chapter" data-level="" data-path="u1-random-variables.html"><a href="u1-random-variables.html#the-assumption-that-licenses-everything"><i class="fa fa-check"></i>The assumption that licenses everything</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="u1-sampling-distribution.html"><a href="u1-sampling-distribution.html"><i class="fa fa-check"></i><b>1.8</b> A population where we know the answer</a>
<ul>
<li class="chapter" data-level="" data-path="u1-sampling-distribution.html"><a href="u1-sampling-distribution.html#what-happens-as-the-sample-grows"><i class="fa fa-check"></i>What happens as the sample grows</a></li>
<li class="chapter" data-level="" data-path="u1-sampling-distribution.html"><a href="u1-sampling-distribution.html#where-these-results-come-from"><i class="fa fa-check"></i>Where these results come from</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="u1-average.html"><a href="u1-average.html"><i class="fa fa-check"></i><b>1.9</b> The average is not the distribution</a></li>
<li class="chapter" data-level="1.10" data-path="u1-what-goes-wrong.html"><a href="u1-what-goes-wrong.html"><i class="fa fa-check"></i><b>1.10</b> What can go wrong before any mathematics</a></li>
<li class="chapter" data-level="1.11" data-path="u1-summary.html"><a href="u1-summary.html"><i class="fa fa-check"></i><b>1.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="one-sample.html"><a href="one-sample.html"><i class="fa fa-check"></i><b>2</b> Hypothesis Testing: One Sample</a>
<ul>
<li class="chapter" data-level="2.1" data-path="os-problem.html"><a href="os-problem.html"><i class="fa fa-check"></i><b>2.1</b> The problem, before any formulas</a></li>
<li class="chapter" data-level="2.2" data-path="os-hypotheses.html"><a href="os-hypotheses.html"><i class="fa fa-check"></i><b>2.2</b> Naming the two hypotheses</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="os-hypotheses.html"><a href="os-hypotheses.html#os-which-hypothesis"><i class="fa fa-check"></i><b>2.2.1</b> Which hypothesis does the claim go in?</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="os-critical.html"><a href="os-critical.html"><i class="fa fa-check"></i><b>2.3</b> How far is too far?</a></li>
<li class="chapter" data-level="2.4" data-path="os-worked.html"><a href="os-worked.html"><i class="fa fa-check"></i><b>2.4</b> The worked example, both ways</a>
<ul>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#on-paper"><i class="fa fa-check"></i>On paper</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#the-same-thing-in-r"><i class="fa fa-check"></i>The same thing in R</a></li>
<li class="chapter" data-level="" data-path="os-worked.html"><a href="os-worked.html#letting-a-package-do-it"><i class="fa fa-check"></i>Letting a package do it</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="os-pvalue.html"><a href="os-pvalue.html"><i class="fa fa-check"></i><b>2.5</b> What a <span class="math inline">\(p\)</span>-value actually says</a></li>
<li class="chapter" data-level="2.6" data-path="os-ci.html"><a href="os-ci.html"><i class="fa fa-check"></i><b>2.6</b> Confidence intervals are the same test in disguise</a></li>
<li class="chapter" data-level="2.7" data-path="os-ttest.html"><a href="os-ttest.html"><i class="fa fa-check"></i><b>2.7</b> When <span class="math inline">\(\sigma\)</span> is unknown: the <span class="math inline">\(t\)</span>-test</a>
<ul>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#settling-the-question-with-the-actual-class"><i class="fa fa-check"></i>Settling the question with the actual class</a></li>
<li class="chapter" data-level="" data-path="os-ttest.html"><a href="os-ttest.html#worked-example"><i class="fa fa-check"></i>Worked example</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="os-onetailed.html"><a href="os-onetailed.html"><i class="fa fa-check"></i><b>2.8</b> One-tailed tests</a>
<ul>
<li class="chapter" data-level="" data-path="os-onetailed.html"><a href="os-onetailed.html#the-one-sided-interval-looks-backwards"><i class="fa fa-check"></i>The one-sided interval looks backwards</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="os-reference.html"><a href="os-reference.html"><i class="fa fa-check"></i><b>2.9</b> Reference tables</a></li>
<li class="chapter" data-level="2.10" data-path="os-exercises.html"><a href="os-exercises.html"><i class="fa fa-check"></i><b>2.10</b> Practice problems</a></li>
<li class="chapter" data-level="2.11" data-path="os-question-bank.html"><a href="os-question-bank.html"><i class="fa fa-check"></i><b>2.11</b> Question bank</a>
<ul>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#multiple-choice"><i class="fa fa-check"></i>Multiple choice</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#short-reasoning"><i class="fa fa-check"></i>Short reasoning</a></li>
<li class="chapter" data-level="" data-path="os-question-bank.html"><a href="os-question-bank.html#numerical"><i class="fa fa-check"></i>Numerical</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="os-summary.html"><a href="os-summary.html"><i class="fa fa-check"></i><b>2.12</b> Summary</a></li>
</ul></li>
<li class="divider"></li>
<li class="toc-after">Kedar Kulkarni · Azim Premji University<br>
<a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistics and Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="u1-lln" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Why do larger samples give more reliable answers?<a href="u1-lln.html#u1-lln" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="question">
<p>What determines how much they vary?</p>
</div>
<p>Figure <a href="u1-frequentist.html#fig:u1-many-plot">1.5</a> answered one important question. Repeating the
survey many times does not produce wildly different
sample means. Instead, the sample means cluster around the population mean.</p>
<p>A natural question follows. What determines how much they vary?</p>
<p>One possibility is the size of the survey itself. Intuition suggests that a
survey of twenty workers should produce averages that vary much more from one
survey to the next than a survey of two thousand workers. But how much
difference does sample size really make?</p>
<p>To find out, let us repeat the experiment from the previous section several
times. Instead of fixing the sample size at 2,000 workers, we consider surveys
of different sizes. For each sample size we draw one thousand independent
samples and compute the average annual earnings.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="u1-lln.html#cb28-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">3</span>)</span>
<span id="cb28-2"><a href="u1-lln.html#cb28-2" tabindex="-1"></a></span>
<span id="cb28-3"><a href="u1-lln.html#cb28-3" tabindex="-1"></a>earn  <span class="ot">&lt;-</span> workers<span class="sc">$</span>annual_earnings</span>
<span id="cb28-4"><a href="u1-lln.html#cb28-4" tabindex="-1"></a>sizes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">100</span>, <span class="dv">500</span>, <span class="dv">2000</span>)</span>
<span id="cb28-5"><a href="u1-lln.html#cb28-5" tabindex="-1"></a></span>
<span id="cb28-6"><a href="u1-lln.html#cb28-6" tabindex="-1"></a>by_size <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, <span class="fu">lapply</span>(sizes, <span class="cf">function</span>(n) {</span>
<span id="cb28-7"><a href="u1-lln.html#cb28-7" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">n =</span> <span class="fu">factor</span>(<span class="fu">paste</span>(<span class="st">&quot;n =&quot;</span>, n), <span class="at">levels =</span> <span class="fu">paste</span>(<span class="st">&quot;n =&quot;</span>, sizes)),</span>
<span id="cb28-8"><a href="u1-lln.html#cb28-8" tabindex="-1"></a>             <span class="at">m =</span> <span class="fu">replicate</span>(<span class="dv">4000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(earn, n, <span class="at">replace =</span> <span class="cn">TRUE</span>))))</span>
<span id="cb28-9"><a href="u1-lln.html#cb28-9" tabindex="-1"></a>}))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:u1-lln-plot"></span>
<img src="stats-econometrics-r_files/figure-html/u1-lln-plot-1.png" alt="Sampling distributions of the sample mean for different sample sizes." width="90%" />
<p class="caption">
Figure 1.6: Sampling distributions of the sample mean for different sample sizes.
</p>
</div>
<p>The pattern is unmistakable.</p>
<p>When the sample contains only a small number of workers, the sample means are
widely dispersed. Some surveys produce averages well above the population mean,
while others fall well below it. The averages vary substantially from one
survey to the next.</p>
<p>As the sample size increases, the sampling distribution becomes progressively
narrower. The sample means remain centred at the population mean, but they
fluctuate much less. Large departures from the population mean become
increasingly uncommon, while averages close to the population mean become
increasingly likely.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="u1-lln.html#cb29-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">tapply</span>(by_size<span class="sc">$</span>m, by_size<span class="sc">$</span>n, sd))</span></code></pre></div>
<pre><code>#&gt;   n = 20  n = 100  n = 500 n = 2000 
#&gt;    22998     9973     4433     2252</code></pre>
<p>This behaviour reflects a simple idea. Every sample contains chance variation.
Some samples happen to include more high-income workers than average, while
others include more low-income workers. In a small sample these random
differences have a noticeable effect on the average. As the sample grows,
unusually high and unusually low observations increasingly offset one another,
and the sample mean settles closer to the population mean.</p>
<p>The behaviour we have just observed is not merely an empirical regularity. It
is one of the most fundamental results in probability theory and forms the
foundation of statistical inference. It is known as the <strong>Law of Large
Numbers</strong>.</p>
<p>In informal terms, the Law of Large Numbers states that as the sample size
increases, the sample mean gets closer and closer to the population mean. Large
samples do not eliminate randomness, but they reduce its influence. Although no
single survey is guaranteed to produce the correct answer, larger surveys are
increasingly likely to do so.</p>
<p>The Law of Large Numbers explains why surveys, opinion polls, clinical trials
and economic censuses can provide reliable information about populations
without observing every individual. The key is not that they observe everyone,
but that they observe enough.</p>
<div class="realworld">
<p>Real demonstrations of the Law of Large Numbers are surprisingly hard to find.
The law concerns what happens when the same random process is repeated a great
many times, and few processes in economic life are repeated identically enough,
often enough, for the convergence to be visible.</p>
<p>The cricket toss is an exception. Before every international match a coin is
tossed, and over nearly a century and a half some teams have accumulated
thousands of these tosses while others have played only a handful.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="u1-lln.html#cb31-1" tabindex="-1"></a>toss <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/cricket-toss.csv&quot;</span>)</span>
<span id="cb31-2"><a href="u1-lln.html#cb31-2" tabindex="-1"></a>keep <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;team&quot;</span>, <span class="st">&quot;span&quot;</span>, <span class="st">&quot;matches&quot;</span>, <span class="st">&quot;pct_toss_won&quot;</span>)</span>
<span id="cb31-3"><a href="u1-lln.html#cb31-3" tabindex="-1"></a></span>
<span id="cb31-4"><a href="u1-lln.html#cb31-4" tabindex="-1"></a><span class="co"># the most and least fortunate teams, and the most experienced</span></span>
<span id="cb31-5"><a href="u1-lln.html#cb31-5" tabindex="-1"></a><span class="fu">rbind</span>(<span class="fu">head</span>(toss[<span class="fu">order</span>(<span class="sc">-</span>toss<span class="sc">$</span>pct_toss_won), keep], <span class="dv">2</span>),</span>
<span id="cb31-6"><a href="u1-lln.html#cb31-6" tabindex="-1"></a>      <span class="fu">head</span>(toss[<span class="fu">order</span>( toss<span class="sc">$</span>pct_toss_won), keep], <span class="dv">2</span>),</span>
<span id="cb31-7"><a href="u1-lln.html#cb31-7" tabindex="-1"></a>      <span class="fu">head</span>(toss[keep], <span class="dv">3</span>))</span></code></pre></div>
<pre><code>#&gt;            team      span matches pct_toss_won
#&gt; 90       Greece 2019-2024      15        80.00
#&gt; 88 Cook Islands 2022-2025      17        70.59
#&gt; 94    Africa XI 2005-2007       6        16.67
#&gt; 91        China 2023-2024      11        27.27
#&gt; 1       England 1877-2025    2124        49.25
#&gt; 2     Australia 1879-2025    2116        51.23
#&gt; 3         India 1932-2025    1926        49.58</code></pre>
<p>Greece has won 80% of its tosses and Africa XI barely one in six, while
England, after 2,124 matches, sits at 49.2%. Nobody is luckier than anybody
else. The teams with extreme records are simply the teams that have played few
matches.</p>
<p>That is the Law of Large Numbers, and the agreement with theory is close. If
the toss is fair, a team with <span class="math inline">\(n\)</span> matches should have a toss-win percentage
scattered around 50 with a standard deviation of <span class="math inline">\(50/\sqrt{n}\)</span> percentage
points. Restricting attention to teams above a given number of matches:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="u1-lln.html#cb33-1" tabindex="-1"></a>lln_toss <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">500</span>), <span class="cf">function</span>(m) {</span>
<span id="cb33-2"><a href="u1-lln.html#cb33-2" tabindex="-1"></a>  x <span class="ot">&lt;-</span> toss[toss<span class="sc">$</span>matches <span class="sc">&gt;=</span> m, ]</span>
<span id="cb33-3"><a href="u1-lln.html#cb33-3" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">min_matches =</span> m,</span>
<span id="cb33-4"><a href="u1-lln.html#cb33-4" tabindex="-1"></a>    <span class="at">teams       =</span> <span class="fu">nrow</span>(x),</span>
<span id="cb33-5"><a href="u1-lln.html#cb33-5" tabindex="-1"></a>    <span class="at">observed_sd =</span> <span class="fu">sd</span>(x<span class="sc">$</span>pct_toss_won),</span>
<span id="cb33-6"><a href="u1-lln.html#cb33-6" tabindex="-1"></a>    <span class="at">predicted   =</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((<span class="dv">50</span> <span class="sc">/</span> <span class="fu">sqrt</span>(x<span class="sc">$</span>matches))<span class="sc">^</span><span class="dv">2</span>)))</span>
<span id="cb33-7"><a href="u1-lln.html#cb33-7" tabindex="-1"></a>}))</span>
<span id="cb33-8"><a href="u1-lln.html#cb33-8" tabindex="-1"></a></span>
<span id="cb33-9"><a href="u1-lln.html#cb33-9" tabindex="-1"></a><span class="fu">round</span>(lln_toss, <span class="dv">2</span>)</span></code></pre></div>
<pre><code>#&gt;      min_matches teams observed_sd predicted
#&gt; [1,]           0    94        8.46      7.91
#&gt; [2,]          50    49        4.92      4.77
#&gt; [3,]         100    27        3.03      3.16
#&gt; [4,]         200    16        2.10      2.05
#&gt; [5,]         500    10        0.85      1.32</code></pre>
<p>The spread of toss-win percentages falls from 8.5 percentage points across all
teams to 0.9 among the ten most experienced — and at every step it tracks the
value the theory predicts. No survey was designed and no experiment was run.
The convergence is simply there in the record of the game.</p>
</div>
<p>Yet Figure <a href="u1-lln.html#fig:u1-lln-plot">1.6</a> reveals another feature that the Law of
Large Numbers does not explain. As the sample size increases, the sampling
distributions not only become narrower — they also become increasingly
bell-shaped. This is surprising because the underlying distribution of earnings
is strongly skewed.</p>
<p>Why should averages of skewed data look approximately normal?</p>
<p>The answer is provided by an even more remarkable result: the <strong>Central Limit
Theorem</strong>.</p>
</div>
<script>
// Solutions are written as plain fenced divs in the source, so the PDF edition
// can typeset them as boxes. On the web they should stay hidden until asked
// for, so wrap each one in a <details> here.
document.addEventListener("DOMContentLoaded", function () {
  document.querySelectorAll("div.answer").forEach(function (div) {
    var d = document.createElement("details");
    d.className = "answer";
    var s = document.createElement("summary");
    s.textContent = "Show the solution";
    d.appendChild(s);
    while (div.firstChild) d.appendChild(div.firstChild);
    div.parentNode.replaceChild(d, div);
  });
});
</script>
            </section>

          </div>
        </div>
      </div>
<a href="u1-frequentist.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="u1-clt.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": false
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/kedarkulkarni1991/stats-econometrics-r/edit/main/01-towards-inferential-statistics.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection",
    "scroll_highlight": true
  },
  "toolbar": {
    "position": "fixed"
  },
  "info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
